.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel sqrtf
    /* 34110 80033510 03E00008 */  jr         $ra
    /* 34114 80033514 46006004 */   sqrt.s    $f0, $f12
    /* 34118 80033518 00000000 */  nop
    /* 3411C 8003351C 00000000 */  nop
.size sqrtf, . - sqrtf
