#ifndef _GM1PGAME_H_
#define _GM1PGAME_H_

#define GM1PGAME_STAGE_MAX_TEAM_COUNT 30
#define GM1PGAME_STAGE_MAX_VARIATIONS_COUNT 12

#define GM1PGAME_STAGE_YOSHI_VARIATIONS_COUNT 6
#define GM1PGAME_STAGE_YOSHI_TEAM_COUNT 18

#define GM1PGAME_STAGE_KIRBY_VARIATIONS_COUNT 7
#define GM1PGAME_STAGE_KIRBY_TEAM_COUNT	8
#define GM1PGAME_STAGE_KIRBY_SIM_COUNT 2				// Number of opponents fought at once

#define GM1PGAME_STAGE_MAX_OPPONENT_COUNT 3

#endif