#ifndef SCENEMGR_ENTRIES_H
#define SCENEMGR_ENTRIES_H

// these will eventually find a home in their actual headers

void mnNoControllerStartScene();
void mnTitleStartScene();
void dbMapsStartScene();
void dbCubeStartScene();
void dbBattleStartScene();
void dbFallsStartScene();
void mnUnusedFightersStartScene();
void mnModeSelectStartScene();
void mn1PModeStartScene();
void mnOptionStartScene();
void mnDataStartScene();
void mnVSModeStartScene();
void mnVSOptionsStartScene();
void mnVSItemSwitchStartScene();
void mnMessageStartScene();
void sc1PChallengerStartScene();
void sc1PStageCardStartScene();
void mnScreenAdjustStartScene();
void vs_css_entry();
void mnStagesStartScene();
void scVSBattleStartScene();
void mvUnknownMarioStartScene();
void sc1PManagerUpdateScene();
void sc1PBonusStageStartScene();
void sc1PTrainingModeStartScene();
void vs_results_entry();
void vs_records_entry();
void char_bkg_info_entry();
void mnN64StartScene();
void intro_firstscene_entry();
void mvPortraitsStartScene();
void intro_focus_mario_entry();
void intro_focus_dk_entry();
void intro_focus_samus_entry();
void intro_focus_fox_entry();
void intro_focus_link_entry();
void intro_focus_yoshi_entry();
void intro_focus_pikachu_entry();
void mvOpeningKirbyStartScene();
void mvOpeningRunStartScene();
void mvOpeningYosterStartScene();
void mvOpeningCliffStartScene();
void mvOpeningStandoffStartScene();
void mvOpeningYamabukiStartScene();
void mvOpeningClashStartScene();
void mvOpeningSectorStartScene();
void mvOpeningJungleStartScene();
void mvOpeningNewcomersStartScene();
void classic_css_entry();
void training_css_entry();
void bonus_css_entry();
void bonus_css_entry();
void mnBackupClearStartScene();
void mvEndingStartScene();
void sc1PContinueStartScene();
void sc1PStageClearStartScene();
void gmStaffrollStartScene();
void mnCongraStartScene();
void mnSoundTestStartScene();
void scExplainStartScene();
void scAutoDemoStartScene();

#endif /* SCENEMGR_ENTRIES_H */
