/*
 * Particle texture bank for EFCommon.
 * ROM: 0xAC9DE0..0xB16C80 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct efcommonTexture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} efcommonTexture_0;

typedef struct efcommonTexture_1
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} efcommonTexture_1;

typedef struct efcommonTexture_2
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][128];
} efcommonTexture_2;

typedef struct efcommonTexture_3
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][128];
} efcommonTexture_3;

typedef struct efcommonTexture_4
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} efcommonTexture_4;

typedef struct efcommonTexture_5
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][128];
} efcommonTexture_5;

typedef struct efcommonTexture_6
{
	LBTextureHeader hdr;
} efcommonTexture_6;

typedef struct efcommonTexture_7
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[2][512];
} efcommonTexture_7;

typedef struct efcommonTexture_8
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][128];
} efcommonTexture_8;

typedef struct efcommonTexture_9
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][256];
} efcommonTexture_9;

typedef struct efcommonTexture_10
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][1024];
} efcommonTexture_10;

typedef struct efcommonTexture_11
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][1024];
} efcommonTexture_11;

typedef struct efcommonTexture_12
{
	LBTextureHeader hdr;
	u32             data[6];
	u8              image_data[6][2048];
} efcommonTexture_12;

typedef struct efcommonTexture_13
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[2][256];
} efcommonTexture_13;

typedef struct efcommonTexture_14
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][1024];
} efcommonTexture_14;

typedef struct efcommonTexture_15
{
	LBTextureHeader hdr;
	u32             data[8];
	u8              image_data[8][512];
} efcommonTexture_15;

typedef struct efcommonTexture_16
{
	LBTextureHeader hdr;
	u32             data[8];
	u8              image_data[7][4096];
} efcommonTexture_16;

typedef struct efcommonTexture_17
{
	LBTextureHeader hdr;
	u32             data[10];
	u8              image_data[10][4096];
} efcommonTexture_17;

typedef struct efcommonTexture_18
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][1024];
} efcommonTexture_18;

typedef struct efcommonTexture_19
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][1024];
} efcommonTexture_19;

typedef struct efcommonTexture_20
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][1024];
} efcommonTexture_20;

typedef struct efcommonTexture_21
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][1024];
} efcommonTexture_21;

typedef struct efcommonTexture_22
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[2][128];
} efcommonTexture_22;

typedef struct efcommonTexture_23
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[4][2304];
} efcommonTexture_23;

typedef struct efcommonTexture_24
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][2048];
} efcommonTexture_24;

typedef struct efcommonTexture_25
{
	LBTextureHeader hdr;
	u32             data[30];
	u8              image_data[15][128];
	u8              palette_data[15][32];
} efcommonTexture_25;

typedef struct efcommonTexture_26
{
	LBTextureHeader hdr;
	u32             data[6];
	u8              image_data[3][128];
	u8              palette_data[3][32];
} efcommonTexture_26;

typedef struct efcommonTexture_27
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][64];
	u8              palette_data[1][32];
} efcommonTexture_27;

typedef struct efcommonTexture_28
{
	LBTextureHeader hdr;
	u32             data[20];
	u8              image_data[20][512];
} efcommonTexture_28;

typedef struct efcommonTexture_29
{
	LBTextureHeader hdr;
	u32             data[10];
	u8              image_data[10][4096];
} efcommonTexture_29;

typedef struct efcommonTexture_30
{
	LBTextureHeader hdr;
	u32             data[10];
	u8              image_data[10][2048];
} efcommonTexture_30;

typedef struct efcommonTexture_31
{
	LBTextureHeader hdr;
	u32             data[6];
	u8              image_data[3][512];
	u8              palette_data[3][32];
} efcommonTexture_31;

typedef struct efcommonTexture_32
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[2][512];
	u8              palette_data[2][32];
} efcommonTexture_32;

typedef struct efcommonTexture_33
{
	LBTextureHeader hdr;
	u32             data[18];
	u8              image_data[9][512];
	u8              palette_data[9][32];
} efcommonTexture_33;

typedef struct efcommonTexture_34
{
	LBTextureHeader hdr;
	u32             data[16];
	u8              image_data[8][512];
	u8              palette_data[8][32];
} efcommonTexture_34;

typedef struct efcommonTexture_35
{
	LBTextureHeader hdr;
	u32             data[16];
	u8              image_data[8][512];
	u8              palette_data[8][32];
} efcommonTexture_35;

typedef struct efcommonTexture_36
{
	LBTextureHeader hdr;
	u32             data[16];
	u8              image_data[8][512];
	u8              palette_data[8][32];
} efcommonTexture_36;

typedef struct efcommonTexture_37
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][128];
	u8              palette_data[1][32];
} efcommonTexture_37;

typedef struct efcommonTexture_38
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][512];
} efcommonTexture_38;

typedef struct efcommonTexture_39
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} efcommonTexture_39;

typedef struct efcommonTexture_40
{
	LBTextureHeader hdr;
	u32             data[10];
	u8              image_data[9][4096];
} efcommonTexture_40;

typedef struct efcommonTexture_41
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][2048];
} efcommonTexture_41;

typedef struct efcommonTexture_42
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[4][1024];
} efcommonTexture_42;

typedef struct efcommonTexture_43
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][1024];
} efcommonTexture_43;

typedef struct efcommonTexture_44
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[2][256];
} efcommonTexture_44;

typedef struct efcommonTexture_45
{
	LBTextureHeader hdr;
	u32             data[10];
	u8              image_data[9][4096];
} efcommonTexture_45;

typedef struct efcommonTexture_46
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][4096];
} efcommonTexture_46;

typedef struct efcommonTxb
{
	s32              textures_num;
	u32              texture_offsets[47];
	efcommonTexture_0 texture_0;
	efcommonTexture_1 texture_1;
	efcommonTexture_2 texture_2;
	efcommonTexture_3 texture_3;
	efcommonTexture_4 texture_4;
	efcommonTexture_5 texture_5;
	efcommonTexture_6 texture_6;
	efcommonTexture_7 texture_7;
	efcommonTexture_8 texture_8;
	efcommonTexture_9 texture_9;
	efcommonTexture_10 texture_10;
	efcommonTexture_11 texture_11;
	efcommonTexture_12 texture_12;
	efcommonTexture_13 texture_13;
	efcommonTexture_14 texture_14;
	efcommonTexture_15 texture_15;
	efcommonTexture_16 texture_16;
	efcommonTexture_17 texture_17;
	efcommonTexture_18 texture_18;
	efcommonTexture_19 texture_19;
	efcommonTexture_20 texture_20;
	efcommonTexture_21 texture_21;
	efcommonTexture_22 texture_22;
	efcommonTexture_23 texture_23;
	efcommonTexture_24 texture_24;
	efcommonTexture_25 texture_25;
	efcommonTexture_26 texture_26;
	efcommonTexture_27 texture_27;
	efcommonTexture_28 texture_28;
	efcommonTexture_29 texture_29;
	efcommonTexture_30 texture_30;
	efcommonTexture_31 texture_31;
	efcommonTexture_32 texture_32;
	efcommonTexture_33 texture_33;
	efcommonTexture_34 texture_34;
	efcommonTexture_35 texture_35;
	efcommonTexture_36 texture_36;
	efcommonTexture_37 texture_37;
	efcommonTexture_38 texture_38;
	efcommonTexture_39 texture_39;
	efcommonTexture_40 texture_40;
	efcommonTexture_41 texture_41;
	efcommonTexture_42 texture_42;
	efcommonTexture_43 texture_43;
	efcommonTexture_44 texture_44;
	efcommonTexture_45 texture_45;
	efcommonTexture_46 texture_46;
} efcommonTxb;

const efcommonTxb dEFCommonTxb = {
	47,
	{
		offsetof(efcommonTxb, texture_0),
		offsetof(efcommonTxb, texture_1),
		offsetof(efcommonTxb, texture_2),
		offsetof(efcommonTxb, texture_3),
		offsetof(efcommonTxb, texture_4),
		offsetof(efcommonTxb, texture_5),
		offsetof(efcommonTxb, texture_6),
		offsetof(efcommonTxb, texture_7),
		offsetof(efcommonTxb, texture_8),
		offsetof(efcommonTxb, texture_9),
		offsetof(efcommonTxb, texture_10),
		offsetof(efcommonTxb, texture_11),
		offsetof(efcommonTxb, texture_12),
		offsetof(efcommonTxb, texture_13),
		offsetof(efcommonTxb, texture_14),
		offsetof(efcommonTxb, texture_15),
		offsetof(efcommonTxb, texture_16),
		offsetof(efcommonTxb, texture_17),
		offsetof(efcommonTxb, texture_18),
		offsetof(efcommonTxb, texture_19),
		offsetof(efcommonTxb, texture_20),
		offsetof(efcommonTxb, texture_21),
		offsetof(efcommonTxb, texture_22),
		offsetof(efcommonTxb, texture_23),
		offsetof(efcommonTxb, texture_24),
		offsetof(efcommonTxb, texture_25),
		offsetof(efcommonTxb, texture_26),
		offsetof(efcommonTxb, texture_27),
		offsetof(efcommonTxb, texture_28),
		offsetof(efcommonTxb, texture_29),
		offsetof(efcommonTxb, texture_30),
		offsetof(efcommonTxb, texture_31),
		offsetof(efcommonTxb, texture_32),
		offsetof(efcommonTxb, texture_33),
		offsetof(efcommonTxb, texture_34),
		offsetof(efcommonTxb, texture_35),
		offsetof(efcommonTxb, texture_36),
		offsetof(efcommonTxb, texture_37),
		offsetof(efcommonTxb, texture_38),
		offsetof(efcommonTxb, texture_39),
		offsetof(efcommonTxb, texture_40),
		offsetof(efcommonTxb, texture_41),
		offsetof(efcommonTxb, texture_42),
		offsetof(efcommonTxb, texture_43),
		offsetof(efcommonTxb, texture_44),
		offsetof(efcommonTxb, texture_45),
		offsetof(efcommonTxb, texture_46),
	},
	{  /* texture_0 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_0.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/efcommon/tex_0_img_0.i4.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_1.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/efcommon/tex_1_img_0.i4.inc.c>
			},
		},
	},
	{  /* texture_2 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_2.image_data),
			offsetof(efcommonTxb, texture_2.image_data[1]),
			offsetof(efcommonTxb, texture_2.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][128] */
			{
				#include <particles/efcommon/tex_2_img_0.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_2_img_1.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_2_img_2.i4.inc.c>
			},
		},
	},
	{  /* texture_3 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_3.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][128] */
			{
				#include <particles/efcommon/tex_3_img_0.i4.inc.c>
			},
		},
	},
	{  /* texture_4 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_4.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/efcommon/tex_4_img_0.i4.inc.c>
			},
		},
	},
	{  /* texture_5 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_5.image_data),
			offsetof(efcommonTxb, texture_5.image_data[1]),
			offsetof(efcommonTxb, texture_5.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][128] */
			{
				#include <particles/efcommon/tex_5_img_0.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_5_img_1.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_5_img_2.i4.inc.c>
			},
		},
	},
	{  /* texture_6 */
		{  /* hdr */
			0,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
	},
	{  /* texture_7 */
		{  /* hdr */
			2,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_7.image_data),
			offsetof(efcommonTxb, texture_7.image_data[1]),
		},
		{  /* image_data[2][512] */
			{
				#include <particles/efcommon/tex_7_img_0.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_7_img_1.i4.inc.c>
			},
		},
	},
	{  /* texture_8 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_8.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][128] */
			{
				#include <particles/efcommon/tex_8_img_0.i4.inc.c>
			},
		},
	},
	{  /* texture_9 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_9.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][256] */
			{
				#include <particles/efcommon/tex_9_img_0.ia4.inc.c>
			},
		},
	},
	{  /* texture_10 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_10.image_data),
			offsetof(efcommonTxb, texture_10.image_data[1]),
			offsetof(efcommonTxb, texture_10.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][1024] */
			{
				#include <particles/efcommon/tex_10_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_10_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_10_img_2.ia8.inc.c>
			},
		},
	},
	{  /* texture_11 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_11.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][1024] */
			{
				#include <particles/efcommon/tex_11_img_0.ia8.inc.c>
			},
		},
	},
	{  /* texture_12 */
		{  /* hdr */
			6,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_12.image_data),
			offsetof(efcommonTxb, texture_12.image_data[1]),
			offsetof(efcommonTxb, texture_12.image_data[2]),
			offsetof(efcommonTxb, texture_12.image_data[3]),
			offsetof(efcommonTxb, texture_12.image_data[4]),
			offsetof(efcommonTxb, texture_12.image_data[5]),
		},
		{  /* image_data[6][2048] */
			{
				#include <particles/efcommon/tex_12_img_0.rgba16.inc.c>
			},
			{
				#include <particles/efcommon/tex_12_img_1.rgba16.inc.c>
			},
			{
				#include <particles/efcommon/tex_12_img_2.rgba16.inc.c>
			},
			{
				#include <particles/efcommon/tex_12_img_3.rgba16.inc.c>
			},
			{
				#include <particles/efcommon/tex_12_img_4.rgba16.inc.c>
			},
			{
				#include <particles/efcommon/tex_12_img_5.rgba16.inc.c>
			},
		},
	},
	{  /* texture_13 */
		{  /* hdr */
			2,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_13.image_data),
			offsetof(efcommonTxb, texture_13.image_data[1]),
		},
		{  /* image_data[2][256] */
			{
				#include <particles/efcommon/tex_13_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_13_img_1.ia8.inc.c>
			},
		},
	},
	{  /* texture_14 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_14.image_data),
			offsetof(efcommonTxb, texture_14.image_data[1]),
			offsetof(efcommonTxb, texture_14.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][1024] */
			{
				#include <particles/efcommon/tex_14_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_14_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_14_img_2.ia8.inc.c>
			},
		},
	},
	{  /* texture_15 */
		{  /* hdr */
			8,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_15.image_data),
			offsetof(efcommonTxb, texture_15.image_data[1]),
			offsetof(efcommonTxb, texture_15.image_data[2]),
			offsetof(efcommonTxb, texture_15.image_data[3]),
			offsetof(efcommonTxb, texture_15.image_data[4]),
			offsetof(efcommonTxb, texture_15.image_data[5]),
			offsetof(efcommonTxb, texture_15.image_data[6]),
			offsetof(efcommonTxb, texture_15.image_data[7]),
		},
		{  /* image_data[8][512] */
			{
				#include <particles/efcommon/tex_15_img_0.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_1.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_2.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_3.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_4.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_5.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_6.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_15_img_7.ia16.inc.c>
			},
		},
	},
	{  /* texture_16 */
		{  /* hdr */
			7,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			64,  /* width */
			64,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_16.image_data),
			offsetof(efcommonTxb, texture_16.image_data[1]),
			offsetof(efcommonTxb, texture_16.image_data[2]),
			offsetof(efcommonTxb, texture_16.image_data[3]),
			offsetof(efcommonTxb, texture_16.image_data[4]),
			offsetof(efcommonTxb, texture_16.image_data[5]),
			offsetof(efcommonTxb, texture_16.image_data[6]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[7][4096] */
			{
				#include <particles/efcommon/tex_16_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_16_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_16_img_2.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_16_img_3.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_16_img_4.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_16_img_5.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_16_img_6.ia8.inc.c>
			},
		},
	},
	{  /* texture_17 */
		{  /* hdr */
			10,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			64,  /* width */
			64,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_17.image_data),
			offsetof(efcommonTxb, texture_17.image_data[1]),
			offsetof(efcommonTxb, texture_17.image_data[2]),
			offsetof(efcommonTxb, texture_17.image_data[3]),
			offsetof(efcommonTxb, texture_17.image_data[4]),
			offsetof(efcommonTxb, texture_17.image_data[5]),
			offsetof(efcommonTxb, texture_17.image_data[6]),
			offsetof(efcommonTxb, texture_17.image_data[7]),
			offsetof(efcommonTxb, texture_17.image_data[8]),
			offsetof(efcommonTxb, texture_17.image_data[9]),
		},
		{  /* image_data[10][4096] */
			{
				#include <particles/efcommon/tex_17_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_2.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_3.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_4.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_5.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_6.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_7.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_8.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_17_img_9.ia8.inc.c>
			},
		},
	},
	{  /* texture_18 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_18.image_data),
			offsetof(efcommonTxb, texture_18.image_data[1]),
			offsetof(efcommonTxb, texture_18.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][1024] */
			{
				#include <particles/efcommon/tex_18_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_18_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_18_img_2.ia8.inc.c>
			},
		},
	},
	{  /* texture_19 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_19.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][1024] */
			{
				#include <particles/efcommon/tex_19_img_0.ia8.inc.c>
			},
		},
	},
	{  /* texture_20 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_20.image_data),
			offsetof(efcommonTxb, texture_20.image_data[1]),
			offsetof(efcommonTxb, texture_20.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][1024] */
			{
				#include <particles/efcommon/tex_20_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_20_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_20_img_2.ia8.inc.c>
			},
		},
	},
	{  /* texture_21 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_21.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][1024] */
			{
				#include <particles/efcommon/tex_21_img_0.ia8.inc.c>
			},
		},
	},
	{  /* texture_22 */
		{  /* hdr */
			2,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_22.image_data),
			offsetof(efcommonTxb, texture_22.image_data[1]),
		},
		{  /* image_data[2][128] */
			{
				#include <particles/efcommon/tex_22_img_0.ia4.inc.c>
			},
			{
				#include <particles/efcommon/tex_22_img_1.ia4.inc.c>
			},
		},
	},
	{  /* texture_23 */
		{  /* hdr */
			4,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			48,  /* width */
			48,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_23.image_data),
			offsetof(efcommonTxb, texture_23.image_data[1]),
			offsetof(efcommonTxb, texture_23.image_data[2]),
			offsetof(efcommonTxb, texture_23.image_data[3]),
		},
		{  /* image_data[4][2304] */
			{
				#include <particles/efcommon/tex_23_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_23_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_23_img_2.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_23_img_3.ia8.inc.c>
			},
		},
	},
	{  /* texture_24 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_24.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][2048] */
			{
				#include <particles/efcommon/tex_24_img_0.ia16.inc.c>
			},
		},
	},
	{  /* texture_25 */
		{  /* hdr */
			15,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_25.image_data),
			offsetof(efcommonTxb, texture_25.image_data[1]),
			offsetof(efcommonTxb, texture_25.image_data[2]),
			offsetof(efcommonTxb, texture_25.image_data[3]),
			offsetof(efcommonTxb, texture_25.image_data[4]),
			offsetof(efcommonTxb, texture_25.image_data[5]),
			offsetof(efcommonTxb, texture_25.image_data[6]),
			offsetof(efcommonTxb, texture_25.image_data[7]),
			offsetof(efcommonTxb, texture_25.image_data[8]),
			offsetof(efcommonTxb, texture_25.image_data[9]),
			offsetof(efcommonTxb, texture_25.image_data[10]),
			offsetof(efcommonTxb, texture_25.image_data[11]),
			offsetof(efcommonTxb, texture_25.image_data[12]),
			offsetof(efcommonTxb, texture_25.image_data[13]),
			offsetof(efcommonTxb, texture_25.image_data[14]),
			offsetof(efcommonTxb, texture_25.palette_data),
			offsetof(efcommonTxb, texture_25.palette_data[1]),
			offsetof(efcommonTxb, texture_25.palette_data[2]),
			offsetof(efcommonTxb, texture_25.palette_data[3]),
			offsetof(efcommonTxb, texture_25.palette_data[4]),
			offsetof(efcommonTxb, texture_25.palette_data[5]),
			offsetof(efcommonTxb, texture_25.palette_data[6]),
			offsetof(efcommonTxb, texture_25.palette_data[7]),
			offsetof(efcommonTxb, texture_25.palette_data[8]),
			offsetof(efcommonTxb, texture_25.palette_data[9]),
			offsetof(efcommonTxb, texture_25.palette_data[10]),
			offsetof(efcommonTxb, texture_25.palette_data[11]),
			offsetof(efcommonTxb, texture_25.palette_data[12]),
			offsetof(efcommonTxb, texture_25.palette_data[13]),
			offsetof(efcommonTxb, texture_25.palette_data[14]),
		},
		{  /* image_data[15][128] */
			{
				#include <particles/efcommon/tex_25_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_2.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_3.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_4.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_5.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_6.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_7.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_8.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_9.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_10.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_11.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_12.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_13.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_img_14.ci4.inc.c>
			},
		},
		{  /* palette_data[15][32] */
			{
				#include <particles/efcommon/tex_25_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_2.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_3.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_4.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_5.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_6.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_7.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_8.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_9.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_10.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_11.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_12.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_13.inc.c>
			},
			{
				#include <particles/efcommon/tex_25_pal_14.inc.c>
			},
		},
	},
	{  /* texture_26 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_26.image_data),
			offsetof(efcommonTxb, texture_26.image_data[1]),
			offsetof(efcommonTxb, texture_26.image_data[2]),
			offsetof(efcommonTxb, texture_26.palette_data),
			offsetof(efcommonTxb, texture_26.palette_data[1]),
			offsetof(efcommonTxb, texture_26.palette_data[2]),
		},
		{  /* image_data[3][128] */
			{
				#include <particles/efcommon/tex_26_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_26_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_26_img_2.ci4.inc.c>
			},
		},
		{  /* palette_data[3][32] */
			{
				#include <particles/efcommon/tex_26_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_26_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_26_pal_2.inc.c>
			},
		},
	},
	{  /* texture_27 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			8,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_27.image_data),
			offsetof(efcommonTxb, texture_27.palette_data),
		},
		{  /* image_data[1][64] */
			{
				#include <particles/efcommon/tex_27_img_0.ci4.inc.c>
			},
		},
		{  /* palette_data[1][32] */
			{
				#include <particles/efcommon/tex_27_pal_0.inc.c>
			},
		},
	},
	{  /* texture_28 */
		{  /* hdr */
			20,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_28.image_data),
			offsetof(efcommonTxb, texture_28.image_data[1]),
			offsetof(efcommonTxb, texture_28.image_data[2]),
			offsetof(efcommonTxb, texture_28.image_data[3]),
			offsetof(efcommonTxb, texture_28.image_data[4]),
			offsetof(efcommonTxb, texture_28.image_data[5]),
			offsetof(efcommonTxb, texture_28.image_data[6]),
			offsetof(efcommonTxb, texture_28.image_data[7]),
			offsetof(efcommonTxb, texture_28.image_data[8]),
			offsetof(efcommonTxb, texture_28.image_data[9]),
			offsetof(efcommonTxb, texture_28.image_data[10]),
			offsetof(efcommonTxb, texture_28.image_data[11]),
			offsetof(efcommonTxb, texture_28.image_data[12]),
			offsetof(efcommonTxb, texture_28.image_data[13]),
			offsetof(efcommonTxb, texture_28.image_data[14]),
			offsetof(efcommonTxb, texture_28.image_data[15]),
			offsetof(efcommonTxb, texture_28.image_data[16]),
			offsetof(efcommonTxb, texture_28.image_data[17]),
			offsetof(efcommonTxb, texture_28.image_data[18]),
			offsetof(efcommonTxb, texture_28.image_data[19]),
		},
		{  /* image_data[20][512] */
			{
				#include <particles/efcommon/tex_28_img_0.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_1.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_2.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_3.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_4.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_5.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_6.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_7.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_8.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_9.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_10.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_11.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_12.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_13.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_14.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_15.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_16.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_17.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_18.i4.inc.c>
			},
			{
				#include <particles/efcommon/tex_28_img_19.i4.inc.c>
			},
		},
	},
	{  /* texture_29 */
		{  /* hdr */
			10,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_32b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_29.image_data),
			offsetof(efcommonTxb, texture_29.image_data[1]),
			offsetof(efcommonTxb, texture_29.image_data[2]),
			offsetof(efcommonTxb, texture_29.image_data[3]),
			offsetof(efcommonTxb, texture_29.image_data[4]),
			offsetof(efcommonTxb, texture_29.image_data[5]),
			offsetof(efcommonTxb, texture_29.image_data[6]),
			offsetof(efcommonTxb, texture_29.image_data[7]),
			offsetof(efcommonTxb, texture_29.image_data[8]),
			offsetof(efcommonTxb, texture_29.image_data[9]),
		},
		{  /* image_data[10][4096] */
			{
				#include <particles/efcommon/tex_29_img_0.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_1.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_2.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_3.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_4.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_5.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_6.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_7.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_8.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_29_img_9.rgba32.inc.c>
			},
		},
	},
	{  /* texture_30 */
		{  /* hdr */
			10,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_30.image_data),
			offsetof(efcommonTxb, texture_30.image_data[1]),
			offsetof(efcommonTxb, texture_30.image_data[2]),
			offsetof(efcommonTxb, texture_30.image_data[3]),
			offsetof(efcommonTxb, texture_30.image_data[4]),
			offsetof(efcommonTxb, texture_30.image_data[5]),
			offsetof(efcommonTxb, texture_30.image_data[6]),
			offsetof(efcommonTxb, texture_30.image_data[7]),
			offsetof(efcommonTxb, texture_30.image_data[8]),
			offsetof(efcommonTxb, texture_30.image_data[9]),
		},
		{  /* image_data[10][2048] */
			{
				#include <particles/efcommon/tex_30_img_0.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_1.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_2.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_3.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_4.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_5.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_6.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_7.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_8.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_30_img_9.ia16.inc.c>
			},
		},
	},
	{  /* texture_31 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_31.image_data),
			offsetof(efcommonTxb, texture_31.image_data[1]),
			offsetof(efcommonTxb, texture_31.image_data[2]),
			offsetof(efcommonTxb, texture_31.palette_data),
			offsetof(efcommonTxb, texture_31.palette_data[1]),
			offsetof(efcommonTxb, texture_31.palette_data[2]),
		},
		{  /* image_data[3][512] */
			{
				#include <particles/efcommon/tex_31_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_31_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_31_img_2.ci4.inc.c>
			},
		},
		{  /* palette_data[3][32] */
			{
				#include <particles/efcommon/tex_31_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_31_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_31_pal_2.inc.c>
			},
		},
	},
	{  /* texture_32 */
		{  /* hdr */
			2,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			64,  /* width */
			16,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_32.image_data),
			offsetof(efcommonTxb, texture_32.image_data[1]),
			offsetof(efcommonTxb, texture_32.palette_data),
			offsetof(efcommonTxb, texture_32.palette_data[1]),
		},
		{  /* image_data[2][512] */
			{
				#include <particles/efcommon/tex_32_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_32_img_1.ci4.inc.c>
			},
		},
		{  /* palette_data[2][32] */
			{
				#include <particles/efcommon/tex_32_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_32_pal_1.inc.c>
			},
		},
	},
	{  /* texture_33 */
		{  /* hdr */
			9,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_33.image_data),
			offsetof(efcommonTxb, texture_33.image_data[1]),
			offsetof(efcommonTxb, texture_33.image_data[2]),
			offsetof(efcommonTxb, texture_33.image_data[3]),
			offsetof(efcommonTxb, texture_33.image_data[4]),
			offsetof(efcommonTxb, texture_33.image_data[5]),
			offsetof(efcommonTxb, texture_33.image_data[6]),
			offsetof(efcommonTxb, texture_33.image_data[7]),
			offsetof(efcommonTxb, texture_33.image_data[8]),
			offsetof(efcommonTxb, texture_33.palette_data),
			offsetof(efcommonTxb, texture_33.palette_data[1]),
			offsetof(efcommonTxb, texture_33.palette_data[2]),
			offsetof(efcommonTxb, texture_33.palette_data[3]),
			offsetof(efcommonTxb, texture_33.palette_data[4]),
			offsetof(efcommonTxb, texture_33.palette_data[5]),
			offsetof(efcommonTxb, texture_33.palette_data[6]),
			offsetof(efcommonTxb, texture_33.palette_data[7]),
			offsetof(efcommonTxb, texture_33.palette_data[8]),
		},
		{  /* image_data[9][512] */
			{
				#include <particles/efcommon/tex_33_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_2.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_3.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_4.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_5.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_6.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_7.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_img_8.ci4.inc.c>
			},
		},
		{  /* palette_data[9][32] */
			{
				#include <particles/efcommon/tex_33_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_2.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_3.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_4.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_5.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_6.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_7.inc.c>
			},
			{
				#include <particles/efcommon/tex_33_pal_8.inc.c>
			},
		},
	},
	{  /* texture_34 */
		{  /* hdr */
			8,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_34.image_data),
			offsetof(efcommonTxb, texture_34.image_data[1]),
			offsetof(efcommonTxb, texture_34.image_data[2]),
			offsetof(efcommonTxb, texture_34.image_data[3]),
			offsetof(efcommonTxb, texture_34.image_data[4]),
			offsetof(efcommonTxb, texture_34.image_data[5]),
			offsetof(efcommonTxb, texture_34.image_data[6]),
			offsetof(efcommonTxb, texture_34.image_data[7]),
			offsetof(efcommonTxb, texture_34.palette_data),
			offsetof(efcommonTxb, texture_34.palette_data[1]),
			offsetof(efcommonTxb, texture_34.palette_data[2]),
			offsetof(efcommonTxb, texture_34.palette_data[3]),
			offsetof(efcommonTxb, texture_34.palette_data[4]),
			offsetof(efcommonTxb, texture_34.palette_data[5]),
			offsetof(efcommonTxb, texture_34.palette_data[6]),
			offsetof(efcommonTxb, texture_34.palette_data[7]),
		},
		{  /* image_data[8][512] */
			{
				#include <particles/efcommon/tex_34_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_2.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_3.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_4.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_5.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_6.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_img_7.ci4.inc.c>
			},
		},
		{  /* palette_data[8][32] */
			{
				#include <particles/efcommon/tex_34_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_2.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_3.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_4.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_5.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_6.inc.c>
			},
			{
				#include <particles/efcommon/tex_34_pal_7.inc.c>
			},
		},
	},
	{  /* texture_35 */
		{  /* hdr */
			8,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_35.image_data),
			offsetof(efcommonTxb, texture_35.image_data[1]),
			offsetof(efcommonTxb, texture_35.image_data[2]),
			offsetof(efcommonTxb, texture_35.image_data[3]),
			offsetof(efcommonTxb, texture_35.image_data[4]),
			offsetof(efcommonTxb, texture_35.image_data[5]),
			offsetof(efcommonTxb, texture_35.image_data[6]),
			offsetof(efcommonTxb, texture_35.image_data[7]),
			offsetof(efcommonTxb, texture_35.palette_data),
			offsetof(efcommonTxb, texture_35.palette_data[1]),
			offsetof(efcommonTxb, texture_35.palette_data[2]),
			offsetof(efcommonTxb, texture_35.palette_data[3]),
			offsetof(efcommonTxb, texture_35.palette_data[4]),
			offsetof(efcommonTxb, texture_35.palette_data[5]),
			offsetof(efcommonTxb, texture_35.palette_data[6]),
			offsetof(efcommonTxb, texture_35.palette_data[7]),
		},
		{  /* image_data[8][512] */
			{
				#include <particles/efcommon/tex_35_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_2.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_3.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_4.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_5.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_6.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_img_7.ci4.inc.c>
			},
		},
		{  /* palette_data[8][32] */
			{
				#include <particles/efcommon/tex_35_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_2.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_3.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_4.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_5.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_6.inc.c>
			},
			{
				#include <particles/efcommon/tex_35_pal_7.inc.c>
			},
		},
	},
	{  /* texture_36 */
		{  /* hdr */
			8,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			0,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_36.image_data),
			offsetof(efcommonTxb, texture_36.image_data[1]),
			offsetof(efcommonTxb, texture_36.image_data[2]),
			offsetof(efcommonTxb, texture_36.image_data[3]),
			offsetof(efcommonTxb, texture_36.image_data[4]),
			offsetof(efcommonTxb, texture_36.image_data[5]),
			offsetof(efcommonTxb, texture_36.image_data[6]),
			offsetof(efcommonTxb, texture_36.image_data[7]),
			offsetof(efcommonTxb, texture_36.palette_data),
			offsetof(efcommonTxb, texture_36.palette_data[1]),
			offsetof(efcommonTxb, texture_36.palette_data[2]),
			offsetof(efcommonTxb, texture_36.palette_data[3]),
			offsetof(efcommonTxb, texture_36.palette_data[4]),
			offsetof(efcommonTxb, texture_36.palette_data[5]),
			offsetof(efcommonTxb, texture_36.palette_data[6]),
			offsetof(efcommonTxb, texture_36.palette_data[7]),
		},
		{  /* image_data[8][512] */
			{
				#include <particles/efcommon/tex_36_img_0.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_1.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_2.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_3.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_4.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_5.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_6.ci4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_img_7.ci4.inc.c>
			},
		},
		{  /* palette_data[8][32] */
			{
				#include <particles/efcommon/tex_36_pal_0.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_1.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_2.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_3.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_4.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_5.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_6.inc.c>
			},
			{
				#include <particles/efcommon/tex_36_pal_7.inc.c>
			},
		},
	},
	{  /* texture_37 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_CI,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_37.image_data),
			offsetof(efcommonTxb, texture_37.palette_data),
		},
		{  /* image_data[1][128] */
			{
				#include <particles/efcommon/tex_37_img_0.ci4.inc.c>
			},
		},
		{  /* palette_data[1][32] */
			{
				#include <particles/efcommon/tex_37_pal_0.inc.c>
			},
		},
	},
	{  /* texture_38 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_38.image_data),
			offsetof(efcommonTxb, texture_38.image_data[1]),
			offsetof(efcommonTxb, texture_38.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][512] */
			{
				#include <particles/efcommon/tex_38_img_0.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_38_img_1.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_38_img_2.ia16.inc.c>
			},
		},
	},
	{  /* texture_39 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_39.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/efcommon/tex_39_img_0.i4.inc.c>
			},
		},
	},
	{  /* texture_40 */
		{  /* hdr */
			9,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_32b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_40.image_data),
			offsetof(efcommonTxb, texture_40.image_data[1]),
			offsetof(efcommonTxb, texture_40.image_data[2]),
			offsetof(efcommonTxb, texture_40.image_data[3]),
			offsetof(efcommonTxb, texture_40.image_data[4]),
			offsetof(efcommonTxb, texture_40.image_data[5]),
			offsetof(efcommonTxb, texture_40.image_data[6]),
			offsetof(efcommonTxb, texture_40.image_data[7]),
			offsetof(efcommonTxb, texture_40.image_data[8]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[9][4096] */
			{
				#include <particles/efcommon/tex_40_img_0.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_1.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_2.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_3.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_4.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_5.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_6.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_7.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_40_img_8.rgba32.inc.c>
			},
		},
	},
	{  /* texture_41 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_41.image_data),
			offsetof(efcommonTxb, texture_41.image_data[1]),
			offsetof(efcommonTxb, texture_41.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][2048] */
			{
				#include <particles/efcommon/tex_41_img_0.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_41_img_1.ia16.inc.c>
			},
			{
				#include <particles/efcommon/tex_41_img_2.ia16.inc.c>
			},
		},
	},
	{  /* texture_42 */
		{  /* hdr */
			4,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_42.image_data),
			offsetof(efcommonTxb, texture_42.image_data[1]),
			offsetof(efcommonTxb, texture_42.image_data[2]),
			offsetof(efcommonTxb, texture_42.image_data[3]),
		},
		{  /* image_data[4][1024] */
			{
				#include <particles/efcommon/tex_42_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_42_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_42_img_2.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_42_img_3.ia8.inc.c>
			},
		},
	},
	{  /* texture_43 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_43.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][1024] */
			{
				#include <particles/efcommon/tex_43_img_0.ia8.inc.c>
			},
		},
	},
	{  /* texture_44 */
		{  /* hdr */
			2,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_44.image_data),
			offsetof(efcommonTxb, texture_44.image_data[1]),
		},
		{  /* image_data[2][256] */
			{
				#include <particles/efcommon/tex_44_img_0.i8.inc.c>
			},
			{
				#include <particles/efcommon/tex_44_img_1.i8.inc.c>
			},
		},
	},
	{  /* texture_45 */
		{  /* hdr */
			9,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_32b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_45.image_data),
			offsetof(efcommonTxb, texture_45.image_data[1]),
			offsetof(efcommonTxb, texture_45.image_data[2]),
			offsetof(efcommonTxb, texture_45.image_data[3]),
			offsetof(efcommonTxb, texture_45.image_data[4]),
			offsetof(efcommonTxb, texture_45.image_data[5]),
			offsetof(efcommonTxb, texture_45.image_data[6]),
			offsetof(efcommonTxb, texture_45.image_data[7]),
			offsetof(efcommonTxb, texture_45.image_data[8]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[9][4096] */
			{
				#include <particles/efcommon/tex_45_img_0.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_1.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_2.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_3.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_4.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_5.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_6.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_7.rgba32.inc.c>
			},
			{
				#include <particles/efcommon/tex_45_img_8.rgba32.inc.c>
			},
		},
	},
	{  /* texture_46 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			64,  /* width */
			64,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(efcommonTxb, texture_46.image_data),
			offsetof(efcommonTxb, texture_46.image_data[1]),
			offsetof(efcommonTxb, texture_46.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][4096] */
			{
				#include <particles/efcommon/tex_46_img_0.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_46_img_1.ia8.inc.c>
			},
			{
				#include <particles/efcommon/tex_46_img_2.ia8.inc.c>
			},
		},
	},
};
