/*
 * Particle script bank for GRHyrule.
 * ROM: 0xB1F960..0xB1FC80 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct grhyruleScript_0
{
	LBScriptHeader hdr;
	u8             bytecode[26];
} grhyruleScript_0;

typedef struct grhyruleScript_1
{
	LBScriptHeader hdr;
	u8             bytecode[44];
} grhyruleScript_1;

typedef struct grhyruleScript_2
{
	LBScriptHeader hdr;
	u8             bytecode[72];
} grhyruleScript_2;

typedef struct grhyruleScript_3
{
	LBScriptHeader hdr;
	u8             bytecode[10];
} grhyruleScript_3;

typedef struct grhyruleScript_4
{
	LBScriptHeader hdr;
	u8             bytecode[24];
} grhyruleScript_4;

typedef struct grhyruleScript_5
{
	LBScriptHeader hdr;
	u8             bytecode[44];
} grhyruleScript_5;

typedef struct grhyruleScript_6
{
	LBScriptHeader hdr;
	u8             bytecode[134];
} grhyruleScript_6;

typedef struct grhyruleScript_7
{
	LBScriptHeader hdr;
	u8             bytecode[10];
} grhyruleScript_7;

typedef struct grhyruleScb
{
	s32              scripts_num;
	u32              script_offsets[8];
	grhyruleScript_0 script_0;
	grhyruleScript_1 script_1;
	grhyruleScript_2 script_2;
	grhyruleScript_3 script_3;
	grhyruleScript_4 script_4;
	grhyruleScript_5 script_5;
	grhyruleScript_6 script_6;
	grhyruleScript_7 script_7;
} grhyruleScb;

const grhyruleScb dGRHyruleScb = {
	8,
	{
		offsetof(grhyruleScb, script_0),
		offsetof(grhyruleScb, script_1),
		offsetof(grhyruleScb, script_2),
		offsetof(grhyruleScb, script_3),
		offsetof(grhyruleScb, script_4),
		offsetof(grhyruleScb, script_5),
		offsetof(grhyruleScb, script_6),
		offsetof(grhyruleScb, script_7),
	},
	{  /* script_0 */
		{  /* hdr */
			2,  /* kind */
			0,  /* texture_id */
			0,  /* generator_lifetime */
			70,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			0.5f,  /* gravity */
			0.999f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			100.0f,  /* unk_0x20 */
			0.6981317f,  /* unk_0x24 */
			-0.05f,  /* update_rate */
			10.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41A00000) /* 20.0 */,
				LBP_F32(0x41F00000) /* 30.0 */,
			lbpTryDeadRand(10),
			lbpEnvColor(),
			lbpWaitLongFrame(35, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(36), 0xFF, 0xFF, 0xFF, 0x00,
			lbpWaitLongFrame(35, 0),
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			0,  /* generator_lifetime */
			15,  /* particle_lifetime */
			0,  /* flags */
			5.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-0.2f,  /* update_rate */
			800.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetVelAngle, LBP_F32(0x3EB2B8C2) /* 0.3490658402442932 */,
			lbpSetSizeRand, LBP_USHORT_S(11),
				LBP_F32(0x41C80000) /* 25.0 */,
				LBP_F32(0x42480000) /* 50.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x28,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(6), 0xFF, 0xFF, 0xFF, 0x64,
			lbpWaitFrame(5, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0xFF, 0xFF, 0xFF, 0x00,
			lbpWaitFrame(10, 0),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			2,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			32,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			0.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 40.0f, 0.0f },  /* vel */
			50.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-0.32f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(1), 0xFF,
			lbpSetSizeLerp, LBP_USHORT_S(3), LBP_F32(0x00000000) /* 0.0 */,
			lbpWaitFrame(2, 4),
			lbpSetSizeRand, LBP_USHORT_S(5),
				LBP_F32(0x43200000) /* 160.0 */,
				LBP_F32(0x42C80000) /* 100.0 */,
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpSetSizeRand, LBP_USHORT_S(3),
				LBP_F32(0x42200000) /* 40.0 */,
				LBP_F32(0x42C80000) /* 100.0 */,
			lbpWaitFrame(2, 2),
			lbpSetSizeLerp, LBP_USHORT_S(25), LBP_F32(0x440C0000) /* 560.0 */,
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(17), 0x00,
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpEnd(),
		},
	},
	{  /* script_3 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			60,  /* generator_lifetime */
			60,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 1.0f, 1.0f, 1.0f },  /* vel */
			1.0f,  /* unk_0x20 */
			0.01745329238474369f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			100.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(1),
			lbpMakeGenerator(2),
			lbpMakeGenerator(0),
			lbpEnd(),
		},
	},
	{  /* script_4 */
		{  /* hdr */
			2,  /* kind */
			0,  /* texture_id */
			60,  /* generator_lifetime */
			60,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			0.5f,  /* gravity */
			0.999f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			100.0f,  /* unk_0x20 */
			0.6981317f,  /* unk_0x24 */
			-0.05f,  /* update_rate */
			10.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41A00000) /* 20.0 */,
				LBP_F32(0x41F00000) /* 30.0 */,
			lbpTryDeadRand(10),
			lbpEnvColor(),
			lbpWaitFrame(30, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(36), 0xFF, 0xFF, 0xFF, 0x00,
			lbpWaitFrame(30, 0),
			lbpEnd(),
		},
	},
	{  /* script_5 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			60,  /* generator_lifetime */
			15,  /* particle_lifetime */
			0,  /* flags */
			5.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-0.2f,  /* update_rate */
			800.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetVelAngle, LBP_F32(0x3EB2B8C2) /* 0.3490658402442932 */,
			lbpSetSizeRand, LBP_USHORT_S(11),
				LBP_F32(0x41C80000) /* 25.0 */,
				LBP_F32(0x42480000) /* 50.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x14,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(6), 0xFF, 0xFF, 0xFF, 0x46,
			lbpWaitFrame(5, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0xFF, 0xFF, 0xFF, 0x00,
			lbpWaitFrame(10, 0),
			lbpEnd(),
		},
	},
	{  /* script_6 */
		{  /* hdr */
			2,  /* kind */
			2,  /* texture_id */
			60,  /* generator_lifetime */
			32,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			0.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 40.0f, 0.0f },  /* vel */
			50.0f,  /* unk_0x20 */
			0.1745329201221466f,  /* unk_0x24 */
			-0.32f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(1), 0xC8,
			lbpSetSizeLerp, LBP_USHORT_S(3), LBP_F32(0x00000000) /* 0.0 */,
			lbpWaitFrame(2, 4),
			lbpSetSizeRand, LBP_USHORT_S(5),
				LBP_F32(0x430C0000) /* 140.0 */,
				LBP_F32(0x42A00000) /* 80.0 */,
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpSetSizeRand, LBP_USHORT_S(3),
				LBP_F32(0x41A00000) /* 20.0 */,
				LBP_F32(0x42A00000) /* 80.0 */,
			lbpWaitFrame(2, 2),
			lbpSetSizeLerp, LBP_USHORT_S(25), LBP_F32(0x44070000) /* 540.0 */,
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(17), 0x00,
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(21), 0x32,
			lbpWaitFrame(2, 4),
			lbpSetSizeRand, LBP_USHORT_S(5),
				LBP_F32(0x42A00000) /* 80.0 */,
				LBP_F32(0x42480000) /* 50.0 */,
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpSetSizeRand, LBP_USHORT_S(3),
				LBP_F32(0x41A00000) /* 20.0 */,
				LBP_F32(0x42480000) /* 50.0 */,
			lbpWaitFrame(2, 2),
			lbpSetSizeLerp, LBP_USHORT_S(23), LBP_F32(0x438C0000) /* 280.0 */,
			lbpWaitFrame(2, 3),
			lbpWaitFrame(2, 4),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(11), 0x00,
			lbpWaitFrame(2, 4),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpEnd(),
		},
	},
	{  /* script_7 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			60,  /* generator_lifetime */
			60,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 1.0f, 1.0f, 1.0f },  /* vel */
			1.0f,  /* unk_0x20 */
			0.01745329238474369f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			100.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(4),
			lbpMakeGenerator(5),
			lbpMakeGenerator(6),
			lbpEnd(),
		},
	},
};
