/*
 * Particle texture bank for GRHyrule.
 * ROM: 0xB1FC80..0xB22980 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct grhyruleTexture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][128];
} grhyruleTexture_0;

typedef struct grhyruleTexture_1
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][1024];
} grhyruleTexture_1;

typedef struct grhyruleTexture_2
{
	LBTextureHeader hdr;
	u32             data[6];
	u8              image_data[5][2048];
} grhyruleTexture_2;

typedef struct grhyruleTxb
{
	s32              textures_num;
	u32              texture_offsets[3];
	grhyruleTexture_0 texture_0;
	grhyruleTexture_1 texture_1;
	grhyruleTexture_2 texture_2;
} grhyruleTxb;

const grhyruleTxb dGRHyruleTxb = {
	3,
	{
		offsetof(grhyruleTxb, texture_0),
		offsetof(grhyruleTxb, texture_1),
		offsetof(grhyruleTxb, texture_2),
	},
	{  /* texture_0 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(grhyruleTxb, texture_0.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][128] */
			{
				#include <particles/grhyrule/tex_0_img_0.ia4.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(grhyruleTxb, texture_1.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][1024] */
			{
				#include <particles/grhyrule/tex_1_img_0.ia8.inc.c>
			},
		},
	},
	{  /* texture_2 */
		{  /* hdr */
			5,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(grhyruleTxb, texture_2.image_data),
			offsetof(grhyruleTxb, texture_2.image_data[1]),
			offsetof(grhyruleTxb, texture_2.image_data[2]),
			offsetof(grhyruleTxb, texture_2.image_data[3]),
			offsetof(grhyruleTxb, texture_2.image_data[4]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[5][2048] */
			{
				#include <particles/grhyrule/tex_2_img_0.rgba16.inc.c>
			},
			{
				#include <particles/grhyrule/tex_2_img_1.rgba16.inc.c>
			},
			{
				#include <particles/grhyrule/tex_2_img_2.rgba16.inc.c>
			},
			{
				#include <particles/grhyrule/tex_2_img_3.rgba16.inc.c>
			},
			{
				#include <particles/grhyrule/tex_2_img_4.rgba16.inc.c>
			},
		},
	},
};
