/*
 * Particle script bank for GRPupupu.
 * ROM: 0xB1E640..0xB1E7E0 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct grpupupuScript_0
{
	LBScriptHeader hdr;
	u8             bytecode[10];
} grpupupuScript_0;

typedef struct grpupupuScript_1
{
	LBScriptHeader hdr;
	u8             bytecode[7];
} grpupupuScript_1;

typedef struct grpupupuScript_2
{
	LBScriptHeader hdr;
	u8             bytecode[44];
} grpupupuScript_2;

typedef struct grpupupuScript_3
{
	LBScriptHeader hdr;
	u8             bytecode[46];
} grpupupuScript_3;

typedef struct grpupupuScript_4
{
	LBScriptHeader hdr;
	u8             bytecode[34];
} grpupupuScript_4;

typedef struct grpupupuScb
{
	s32              scripts_num;
	u32              script_offsets[5];
	grpupupuScript_0 script_0;
	grpupupuScript_1 script_1;
	grpupupuScript_2 script_2;
	grpupupuScript_3 script_3;
	grpupupuScript_4 script_4;
} grpupupuScb;

const grpupupuScb dGRPupupuScb = {
	5,
	{
		offsetof(grpupupuScb, script_0),
		offsetof(grpupupuScb, script_1),
		offsetof(grpupupuScb, script_2),
		offsetof(grpupupuScb, script_3),
		offsetof(grpupupuScb, script_4),
	},
	{  /* script_0 */
		{  /* hdr */
			0,  /* kind */
			2,  /* texture_id */
			1,  /* generator_lifetime */
			100,  /* particle_lifetime */
			0,  /* flags */
			0.2f,  /* gravity */
			0.98f,  /* friction */
			{ 0.0f, 15.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			0.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(4),
			lbpSetReturn(),
			lbpMakeGenerator(2),
			lbpWait(20),
			lbpReturn(),
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			2,  /* texture_id */
			1,  /* generator_lifetime */
			20,  /* particle_lifetime */
			0,  /* flags */
			0.2f,  /* gravity */
			0.98f,  /* friction */
			{ 40.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			0.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetReturn(),
			lbpMakeGenerator(3),
			lbpWait(20),
			lbpReturn(),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			0,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			64,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			-0.5f,  /* gravity */
			0.999f,  /* friction */
			{ 60.0f, -5.0f, 0.0f },  /* vel */
			5.0f,  /* unk_0x20 */
			0.1745329201221466f,  /* unk_0x24 */
			-0.02f,  /* update_rate */
			70.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetVelAngle, LBP_F32(0x3F060A92) /* 0.5235987901687622 */,
			lbpAddPosRand,
				LBP_F32(0x43FA0000) /* 500.0 */,
				LBP_F32(0x42C80000) /* 100.0 */,
				LBP_F32(0x00000000) /* 0.0 */,
			lbpSetLoop(6),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpLoop(),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(17), 0x00,
			lbpSetLoop(2),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(2, 2),
			lbpWaitFrame(2, 3),
			lbpLoop(),
			lbpEnd(),
		},
	},
	{  /* script_3 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			0,  /* generator_lifetime */
			20,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			-0.8f,  /* gravity */
			1.02f,  /* friction */
			{ 60.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-0.1f,  /* update_rate */
			100.0f,  /* size */
		},
		{  /* bytecode */
			lbpAddPosRand,
				LBP_F32(0x43FA0000) /* 500.0 */,
				LBP_F32(0x00000000) /* 0.0 */,
				LBP_F32(0x00000000) /* 0.0 */,
			lbpSetSizeRand, LBP_USHORT_S(16),
				LBP_F32(0x43160000) /* 150.0 */,
				LBP_F32(0x43480000) /* 200.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xE6, 0xC6, 0x8C, 0x64,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(11), 0x78,
			lbpWaitFrame(10, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(11), 0x00,
			lbpWaitFrame(10, 0),
			lbpEnd(),
		},
	},
	{  /* script_4 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			0,  /* generator_lifetime */
			100,  /* particle_lifetime */
			LBPARTICLE_FLAG_FRICTION,  /* flags */
			-1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 100.0f, 3.0f, 0.0f },  /* vel */
			20.0f,  /* unk_0x20 */
			0.1745329201221466f,  /* unk_0x24 */
			-0.25f,  /* update_rate */
			10.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetSizeRand, LBP_USHORT_S(17),
				LBP_F32(0x43960000) /* 300.0 */,
				LBP_F32(0x42480000) /* 50.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xC7, 0xF9, 0xFF, 0xFF,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x00,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(9), 0xC8,
			lbpWaitFrame(8, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(9), 0x00,
			lbpWaitFrame(8, 0),
			lbpEnd(),
		},
	},
};
