/*
 * Particle texture bank for GRPupupu.
 * ROM: 0xB1E7E0..0xB1F960 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct grpupupuTexture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][2048];
} grpupupuTexture_0;

typedef struct grpupupuTexture_1
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][256];
} grpupupuTexture_1;

typedef struct grpupupuTexture_2
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[4][512];
} grpupupuTexture_2;

typedef struct grpupupuTxb
{
	s32              textures_num;
	u32              texture_offsets[3];
	grpupupuTexture_0 texture_0;
	grpupupuTexture_1 texture_1;
	grpupupuTexture_2 texture_2;
} grpupupuTxb;

const grpupupuTxb dGRPupupuTxb = {
	3,
	{
		offsetof(grpupupuTxb, texture_0),
		offsetof(grpupupuTxb, texture_1),
		offsetof(grpupupuTxb, texture_2),
	},
	{  /* texture_0 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(grpupupuTxb, texture_0.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][2048] */
			{
				#include <particles/grpupupu/tex_0_img_0.ia16.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(grpupupuTxb, texture_1.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][256] */
			{
				#include <particles/grpupupu/tex_1_img_0.i8.inc.c>
			},
		},
	},
	{  /* texture_2 */
		{  /* hdr */
			4,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(grpupupuTxb, texture_2.image_data),
			offsetof(grpupupuTxb, texture_2.image_data[1]),
			offsetof(grpupupuTxb, texture_2.image_data[2]),
			offsetof(grpupupuTxb, texture_2.image_data[3]),
		},
		{  /* image_data[4][512] */
			{
				#include <particles/grpupupu/tex_2_img_0.rgba16.inc.c>
			},
			{
				#include <particles/grpupupu/tex_2_img_1.rgba16.inc.c>
			},
			{
				#include <particles/grpupupu/tex_2_img_2.rgba16.inc.c>
			},
			{
				#include <particles/grpupupu/tex_2_img_3.rgba16.inc.c>
			},
		},
	},
};
