/*
 * Particle texture bank for GRYoster.
 * ROM: 0xB22A00..0xB22C30 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct gryosterTexture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} gryosterTexture_0;

typedef struct gryosterTxb
{
	s32              textures_num;
	u32              texture_offsets[1];
	gryosterTexture_0 texture_0;
} gryosterTxb;

const gryosterTxb dGRYosterTxb = {
	1,
	{
		offsetof(gryosterTxb, texture_0),
	},
	{  /* texture_0 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(gryosterTxb, texture_0.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/gryoster/tex_0_img_0.i4.inc.c>
			},
		},
	},
};
