/*
 * Particle script bank for ITCommon.
 * ROM: 0xB1BCA0..0xB1BDE0 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct itcommonScript_0
{
	LBScriptHeader hdr;
	u8             bytecode[36];
} itcommonScript_0;

typedef struct itcommonScript_1
{
	LBScriptHeader hdr;
	u8             bytecode[7];
} itcommonScript_1;

typedef struct itcommonScript_2
{
	LBScriptHeader hdr;
	u8             bytecode[107];
} itcommonScript_2;

typedef struct itcommonScb
{
	s32              scripts_num;
	u32              script_offsets[3];
	itcommonScript_0 script_0;
	itcommonScript_1 script_1;
	itcommonScript_2 script_2;
} itcommonScb;

const itcommonScb dITCommonScb = {
	3,
	{
		offsetof(itcommonScb, script_0),
		offsetof(itcommonScb, script_1),
		offsetof(itcommonScb, script_2),
	},
	{  /* script_0 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			60,  /* generator_lifetime */
			40,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			0.999f,  /* friction */
			{ 0.0f, 7.8f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.8726646304130554f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			195.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetSizeRand, LBP_USHORT_S(41),
				LBP_F32(0x43C30000) /* 390.0 */,
				LBP_F32(0x44124000) /* 585.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0x73, 0x6B, 0x01, 0x64,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xA3, 0x00, 0x15,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(21), 0x96,
			lbpSetEnvBlend(LBP_A), LBP_USHORT_S(41), 0x00,
			lbpWaitFrame(20, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(21), 0x00,
			lbpWaitFrame(20, 0),
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			60,  /* generator_lifetime */
			60,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 1.0f, 1.0f, 1.0f },  /* vel */
			1.0f,  /* unk_0x20 */
			0.01745329238474369f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			100.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeID(2),
			lbpMakeID(0),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			60,  /* generator_lifetime */
			31,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			0.999f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			117.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetVelAngle, LBP_F32(0x3D56774F) /* 0.05235987529158592 */,
			lbpSetSizeRand, LBP_USHORT_S(32),
				LBP_F32(0x43610000) /* 225.0 */,
				LBP_F32(0x439C0000) /* 312.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(0), LBP_USHORT_S(1),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xF3, 0x82,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(8), 0xFF, 0x99, 0x00,
			lbpWaitFrame(2, 0),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(2, 0),
			lbpWaitFrame(1, 1),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(8), 0xFF, 0xF3, 0x82,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xFF, 0x44, 0x00,
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 0),
			lbpWaitFrame(2, 1),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(4), 0xFF, 0x02, 0x02,
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 0),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 0),
			lbpWaitFrame(2, 1),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0xD1, 0x02, 0x09, 0x32,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xA8, 0x00, 0x0E,
			lbpWaitFrame(2, 2),
			lbpWaitFrame(1, 0),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(2, 3),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(6), 0x00, 0x00, 0x00, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(6), 0x00, 0x00, 0x00, 0x00,
			lbpWaitFrame(5, 3),
			lbpEnd(),
		},
	},
};
