/*
 * Particle texture bank for ITCommon.
 * ROM: 0xB1BDE0..0xB1E640 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct itcommonTexture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][2048];
} itcommonTexture_0;

typedef struct itcommonTexture_1
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[4][2048];
} itcommonTexture_1;

typedef struct itcommonTxb
{
	s32              textures_num;
	u32              texture_offsets[2];
	u8               _pad_after_offsets[4];
	itcommonTexture_0 texture_0;
	itcommonTexture_1 texture_1;
} itcommonTxb;

const itcommonTxb dITCommonTxb = {
	2,
	{
		offsetof(itcommonTxb, texture_0),
		offsetof(itcommonTxb, texture_1),
	},
	{ 0x00, 0x00, 0x28, 0x60 },  /* _pad_after_offsets (non-zero in original) */
	{  /* texture_0 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(itcommonTxb, texture_0.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][2048] */
			{
				#include <particles/itcommon/tex_0_img_0.ia16.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			4,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(itcommonTxb, texture_1.image_data),
			offsetof(itcommonTxb, texture_1.image_data[1]),
			offsetof(itcommonTxb, texture_1.image_data[2]),
			offsetof(itcommonTxb, texture_1.image_data[3]),
		},
		{  /* image_data[4][2048] */
			{
				#include <particles/itcommon/tex_1_img_0.rgba16.inc.c>
			},
			{
				#include <particles/itcommon/tex_1_img_1.rgba16.inc.c>
			},
			{
				#include <particles/itcommon/tex_1_img_2.rgba16.inc.c>
			},
			{
				#include <particles/itcommon/tex_1_img_3.rgba16.inc.c>
			},
		},
	},
};
