/*
 * Particle script bank for MNTitle.
 * ROM: 0xB22C30..0xB22D40 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct mntitleScript_0
{
	LBScriptHeader hdr;
	u8             bytecode[41];
} mntitleScript_0;

typedef struct mntitleScript_1
{
	LBScriptHeader hdr;
	u8             bytecode[28];
} mntitleScript_1;

typedef struct mntitleScript_2
{
	LBScriptHeader hdr;
	u8             bytecode[28];
} mntitleScript_2;

typedef struct mntitleScb
{
	s32              scripts_num;
	u32              script_offsets[3];
	mntitleScript_0 script_0;
	mntitleScript_1 script_1;
	mntitleScript_2 script_2;
} mntitleScb;

const mntitleScb dMNTitleScb = {
	3,
	{
		offsetof(mntitleScb, script_0),
		offsetof(mntitleScb, script_1),
		offsetof(mntitleScb, script_2),
	},
	{  /* script_0 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			100,  /* generator_lifetime */
			28,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			0.95f,  /* friction */
			{ 30.0f, 30.0f, 0.0f },  /* vel */
			-400.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			3.0f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x64,
			lbpSetSizeLerp, LBP_USHORT_S(1), LBP_F32(0x43160000) /* 150.0 */,
			lbpSetSizeLerp, LBP_USHORT_S(27), LBP_F32(0x43480000) /* 200.0 */,
			lbpWaitFrame(3, 0),
			lbpWaitFrame(3, 1),
			lbpWaitFrame(3, 2),
			lbpWaitFrame(3, 3),
			lbpWaitFrame(3, 4),
			lbpWaitFrame(3, 5),
			lbpWaitFrame(3, 6),
			lbpWaitFrame(3, 7),
			lbpSetSizeLerp, LBP_USHORT_S(28), LBP_F32(0x43160000) /* 150.0 */,
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			1,  /* generator_lifetime */
			12,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			0.9f,  /* friction */
			{ 0.0f, -30.0f, 30.0f },  /* vel */
			100.0f,  /* unk_0x20 */
			0.5235988f,  /* unk_0x24 */
			-10.0f,  /* update_rate */
			20.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFA, 0xF3, 0xFA, 0xFF,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(14), 0x11, 0xD0, 0xFA, 0xFF,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(17), 0x08, 0x00, 0xFF, 0x1E,
			lbpEnvColor(),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0x05, 0xB0, 0xFF,
			lbpWaitFrame(0, 0),
			lbpWait(12),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			1,  /* generator_lifetime */
			12,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY | LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			0.9f,  /* friction */
			{ -30.0f, 0.0f, 30.0f },  /* vel */
			100.0f,  /* unk_0x20 */
			0.5235988f,  /* unk_0x24 */
			-10.0f,  /* update_rate */
			20.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFA, 0xF3, 0xFA, 0xFF,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(14), 0x11, 0xD0, 0xFA, 0xFF,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(17), 0x08, 0x00, 0xFF, 0x1E,
			lbpEnvColor(),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0x05, 0xB0, 0xFF,
			lbpWaitFrame(0, 0),
			lbpWait(12),
			lbpEnd(),
		},
	},
};
