/*
 * Particle texture bank for MNTitle.
 * ROM: 0xB22D40..0xB277B0 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct mntitleTexture_0
{
	LBTextureHeader hdr;
	u32             data[10];
	u8              image_data[9][2048];
} mntitleTexture_0;

typedef struct mntitleTexture_1
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} mntitleTexture_1;

typedef struct mntitleTxb
{
	s32              textures_num;
	u32              texture_offsets[2];
	u8               _pad_after_offsets[4];
	mntitleTexture_0 texture_0;
	mntitleTexture_1 texture_1;
} mntitleTxb;

const mntitleTxb dMNTitleTxb = {
	2,
	{
		offsetof(mntitleTxb, texture_0),
		offsetof(mntitleTxb, texture_1),
	},
	{ 0, 0, 0, 0 },  /* _pad_after_offsets */
	{  /* texture_0 */
		{  /* hdr */
			9,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(mntitleTxb, texture_0.image_data),
			offsetof(mntitleTxb, texture_0.image_data[1]),
			offsetof(mntitleTxb, texture_0.image_data[2]),
			offsetof(mntitleTxb, texture_0.image_data[3]),
			offsetof(mntitleTxb, texture_0.image_data[4]),
			offsetof(mntitleTxb, texture_0.image_data[5]),
			offsetof(mntitleTxb, texture_0.image_data[6]),
			offsetof(mntitleTxb, texture_0.image_data[7]),
			offsetof(mntitleTxb, texture_0.image_data[8]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[9][2048] */
			{
				#include <particles/mntitle/tex_0_img_0.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_1.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_2.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_3.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_4.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_5.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_6.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_7.rgba16.inc.c>
			},
			{
				#include <particles/mntitle/tex_0_img_8.rgba16.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(mntitleTxb, texture_1.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/mntitle/tex_1_img_0.i4.inc.c>
			},
		},
	},
};
