/*
 * Particle script bank for ParticlesUnk0.
 * ROM: 0xB16C80..0xB17060 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct particles_unk0Script_0
{
	LBScriptHeader hdr;
	u8             bytecode[22];
} particles_unk0Script_0;

typedef struct particles_unk0Script_1
{
	LBScriptHeader hdr;
	u8             bytecode[35];
} particles_unk0Script_1;

typedef struct particles_unk0Script_2
{
	LBScriptHeader hdr;
	u8             bytecode[7];
} particles_unk0Script_2;

typedef struct particles_unk0Script_3
{
	LBScriptHeader hdr;
	u8             bytecode[22];
} particles_unk0Script_3;

typedef struct particles_unk0Script_4
{
	LBScriptHeader hdr;
	u8             bytecode[35];
} particles_unk0Script_4;

typedef struct particles_unk0Script_5
{
	LBScriptHeader hdr;
	u8             bytecode[7];
} particles_unk0Script_5;

typedef struct particles_unk0Script_6
{
	LBScriptHeader hdr;
	u8             bytecode[22];
} particles_unk0Script_6;

typedef struct particles_unk0Script_7
{
	LBScriptHeader hdr;
	u8             bytecode[24];
} particles_unk0Script_7;

typedef struct particles_unk0Script_8
{
	LBScriptHeader hdr;
	u8             bytecode[27];
} particles_unk0Script_8;

typedef struct particles_unk0Script_9
{
	LBScriptHeader hdr;
	u8             bytecode[27];
} particles_unk0Script_9;

typedef struct particles_unk0Script_10
{
	LBScriptHeader hdr;
	u8             bytecode[24];
} particles_unk0Script_10;

typedef struct particles_unk0Script_11
{
	LBScriptHeader hdr;
	u8             bytecode[24];
} particles_unk0Script_11;

typedef struct particles_unk0Script_12
{
	LBScriptHeader hdr;
	u8             bytecode[19];
} particles_unk0Script_12;

typedef struct particles_unk0Scb
{
	s32              scripts_num;
	u32              script_offsets[13];
	particles_unk0Script_0 script_0;
	particles_unk0Script_1 script_1;
	particles_unk0Script_2 script_2;
	particles_unk0Script_3 script_3;
	particles_unk0Script_4 script_4;
	particles_unk0Script_5 script_5;
	particles_unk0Script_6 script_6;
	particles_unk0Script_7 script_7;
	particles_unk0Script_8 script_8;
	particles_unk0Script_9 script_9;
	particles_unk0Script_10 script_10;
	particles_unk0Script_11 script_11;
	particles_unk0Script_12 script_12;
} particles_unk0Scb;

const particles_unk0Scb dParticlesUnk0Scb = {
	13,
	{
		offsetof(particles_unk0Scb, script_0),
		offsetof(particles_unk0Scb, script_1),
		offsetof(particles_unk0Scb, script_2),
		offsetof(particles_unk0Scb, script_3),
		offsetof(particles_unk0Scb, script_4),
		offsetof(particles_unk0Scb, script_5),
		offsetof(particles_unk0Scb, script_6),
		offsetof(particles_unk0Scb, script_7),
		offsetof(particles_unk0Scb, script_8),
		offsetof(particles_unk0Scb, script_9),
		offsetof(particles_unk0Scb, script_10),
		offsetof(particles_unk0Scb, script_11),
		offsetof(particles_unk0Scb, script_12),
	},
	{  /* script_0 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			20,  /* generator_lifetime */
			11,  /* particle_lifetime */
			LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			1.05f,  /* friction */
			{ 0.0f, 0.0f, 42.0f },  /* vel */
			-700.0f,  /* unk_0x20 */
			4.712389f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x14,
			lbpWaitFrame(0, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(13), 0xFF, 0xFF, 0xFF, 0xFF,
			lbpSetSizeLerp, LBP_USHORT_S(13), LBP_F32(0x42480000) /* 50.0 */,
			lbpWait(14),
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			1,  /* generator_lifetime */
			36,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			520.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x80,
			lbpEnvColor(),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xC7, 0xF6, 0xFF,
			lbpMaskST(),
			lbpSetLoop(3),
			lbpSetSizeLerp, LBP_USHORT_S(1), LBP_F32(0x43D20000) /* 420.0 */,
			lbpSetSizeLerp, LBP_USHORT_S(13), LBP_F32(0x42480000) /* 50.0 */,
			lbpWaitFrame(3, 2),
			lbpWaitFrame(3, 1),
			lbpWaitFrame(3, 0),
			lbpLoop(),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			1,  /* generator_lifetime */
			1,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			200.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(0),
			lbpMakeGenerator(1),
			lbpEnd(),
		},
	},
	{  /* script_3 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			20,  /* generator_lifetime */
			10,  /* particle_lifetime */
			LBPARTICLE_FLAG_FRICTION,  /* flags */
			1.0f,  /* gravity */
			1.05f,  /* friction */
			{ 0.0f, 0.0f, 35.0f },  /* vel */
			-30.0f,  /* unk_0x20 */
			1.5707963f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0xFF,
			lbpWaitFrame(0, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(13), 0xFF, 0xFF, 0xFF, 0x1E,
			lbpSetSizeLerp, LBP_USHORT_S(13), LBP_F32(0x42480000) /* 50.0 */,
			lbpWait(14),
			lbpEnd(),
		},
	},
	{  /* script_4 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			1,  /* generator_lifetime */
			36,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			520.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF, 0x80,
			lbpEnvColor(),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xC7, 0xF6, 0xFF,
			lbpMaskST(),
			lbpSetLoop(3),
			lbpSetSizeLerp, LBP_USHORT_S(1), LBP_F32(0x42480000) /* 50.0 */,
			lbpSetSizeLerp, LBP_USHORT_S(13), LBP_F32(0x43D20000) /* 420.0 */,
			lbpWaitFrame(3, 0),
			lbpWaitFrame(3, 1),
			lbpWaitFrame(3, 2),
			lbpLoop(),
			lbpEnd(),
		},
	},
	{  /* script_5 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			1,  /* generator_lifetime */
			1,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			200.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(3),
			lbpMakeGenerator(4),
			lbpEnd(),
		},
	},
	{  /* script_6 */
		{  /* hdr */
			3,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			15,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			2.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			500.0f,  /* unk_0x20 */
			-4.712389f,  /* unk_0x24 */
			-0.1f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41F00000) /* 30.0 */,
				LBP_F32(0x41A00000) /* 20.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(1), 0xC8,
			lbpWaitFrame(10, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(6), 0x00,
			lbpWaitFrame(5, 0),
			lbpEnd(),
		},
	},
	{  /* script_7 */
		{  /* hdr */
			3,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			20,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			2.5f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			500.0f,  /* unk_0x20 */
			-4.712389f,  /* unk_0x24 */
			-0.2f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPos(LBP_Y), LBP_F32(0xC2C80000) /* -100.0 */,
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41F00000) /* 30.0 */,
				LBP_F32(0x41A00000) /* 20.0 */,
			lbpEnvColor(),
			lbpWaitFrame(15, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(6), 0x00,
			lbpWaitFrame(5, 0),
			lbpEnd(),
		},
	},
	{  /* script_8 */
		{  /* hdr */
			3,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			20,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			2.2f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			-500.0f,  /* unk_0x20 */
			-4.886922f,  /* unk_0x24 */
			-0.1f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPos(LBP_Y), LBP_F32(0xC3480000) /* -200.0 */,
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41F00000) /* 30.0 */,
				LBP_F32(0x41A00000) /* 20.0 */,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(1), 0xC8,
			lbpEnvColor(),
			lbpWaitFrame(15, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(6), 0x00,
			lbpWaitFrame(5, 0),
			lbpEnd(),
		},
	},
	{  /* script_9 */
		{  /* hdr */
			3,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			15,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			2.3f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			-500.0f,  /* unk_0x20 */
			-5.2359877f,  /* unk_0x24 */
			-0.1f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPos(LBP_Y), LBP_F32(0xC3960000) /* -300.0 */,
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41F00000) /* 30.0 */,
				LBP_F32(0x41A00000) /* 20.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(1), 0xC8,
			lbpWaitFrame(10, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(6), 0x00,
			lbpWaitFrame(5, 0),
			lbpEnd(),
		},
	},
	{  /* script_10 */
		{  /* hdr */
			3,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			13,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			3.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 25.0f, 0.0f },  /* vel */
			500.0f,  /* unk_0x20 */
			-5.2359877f,  /* unk_0x24 */
			-0.1f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPos(LBP_Y), LBP_F32(0xC3C80000) /* -400.0 */,
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41F00000) /* 30.0 */,
				LBP_F32(0x41A00000) /* 20.0 */,
			lbpEnvColor(),
			lbpWaitFrame(8, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(6), 0x00,
			lbpWaitFrame(5, 0),
			lbpEnd(),
		},
	},
	{  /* script_11 */
		{  /* hdr */
			3,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			10,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			4.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 35.0f, 0.0f },  /* vel */
			500.0f,  /* unk_0x20 */
			-5.323254f,  /* unk_0x24 */
			-0.1f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPos(LBP_Y), LBP_F32(0xC3FA0000) /* -500.0 */,
			lbpSetSizeRand, LBP_USHORT_S(1),
				LBP_F32(0x41F00000) /* 30.0 */,
				LBP_F32(0x41A00000) /* 20.0 */,
			lbpEnvColor(),
			lbpWaitFrame(6, 0),
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(5), 0x00,
			lbpWaitFrame(4, 0),
			lbpEnd(),
		},
	},
	{  /* script_12 */
		{  /* hdr */
			0,  /* kind */
			2,  /* texture_id */
			0,  /* generator_lifetime */
			1,  /* particle_lifetime */
			0,  /* flags */
			0.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			0.0f,  /* update_rate */
			0.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(11),
			lbpMakeGenerator(10),
			lbpMakeGenerator(9),
			lbpMakeGenerator(8),
			lbpMakeGenerator(7),
			lbpMakeGenerator(6),
			lbpEnd(),
		},
	},
};
