/*
 * Particle texture bank for ParticlesUnk2.
 * ROM: 0xB19850..0xB1BCA0 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct particles_unk2Texture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[2][4096];
} particles_unk2Texture_0;

typedef struct particles_unk2Texture_1
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][1024];
} particles_unk2Texture_1;

typedef struct particles_unk2Txb
{
	s32              textures_num;
	u32              texture_offsets[2];
	u8               _pad_after_offsets[4];
	particles_unk2Texture_0 texture_0;
	particles_unk2Texture_1 texture_1;
} particles_unk2Txb;

const particles_unk2Txb dParticlesUnk2Txb = {
	2,
	{
		offsetof(particles_unk2Txb, texture_0),
		offsetof(particles_unk2Txb, texture_1),
	},
	{ 0, 0, 0, 0 },  /* _pad_after_offsets */
	{  /* texture_0 */
		{  /* hdr */
			2,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			64,  /* width */
			64,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk2Txb, texture_0.image_data),
			offsetof(particles_unk2Txb, texture_0.image_data[1]),
		},
		{  /* image_data[2][4096] */
			{
				#include <particles/particles_unk2/tex_0_img_0.ia8.inc.c>
			},
			{
				#include <particles/particles_unk2/tex_0_img_1.ia8.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk2Txb, texture_1.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][1024] */
			{
				#include <particles/particles_unk2/tex_1_img_0.ia8.inc.c>
			},
		},
	},
};
