/*
 * Particle texture bank for ParticlesUnk0.
 * ROM: 0xB17060..0xB174A0 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct particles_unk0Texture_0
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][512];
} particles_unk0Texture_0;

typedef struct particles_unk0Texture_1
{
	LBTextureHeader hdr;
	u32             data[4];
	u8              image_data[3][128];
} particles_unk0Texture_1;

typedef struct particles_unk0Texture_2
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][64];
} particles_unk0Texture_2;

typedef struct particles_unk0Txb
{
	s32              textures_num;
	u32              texture_offsets[3];
	particles_unk0Texture_0 texture_0;
	particles_unk0Texture_1 texture_1;
	particles_unk0Texture_2 texture_2;
} particles_unk0Txb;

const particles_unk0Txb dParticlesUnk0Txb = {
	3,
	{
		offsetof(particles_unk0Txb, texture_0),
		offsetof(particles_unk0Txb, texture_1),
		offsetof(particles_unk0Txb, texture_2),
	},
	{  /* texture_0 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk0Txb, texture_0.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][512] */
			{
				#include <particles/particles_unk0/tex_0_img_0.ia4.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			3,  /* count */
			G_IM_FMT_I,  /* fmt */
			G_IM_SIZ_4b,  /* siz */
			16,  /* width */
			16,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk0Txb, texture_1.image_data),
			offsetof(particles_unk0Txb, texture_1.image_data[1]),
			offsetof(particles_unk0Txb, texture_1.image_data[2]),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[3][128] */
			{
				#include <particles/particles_unk0/tex_1_img_0.i4.inc.c>
			},
			{
				#include <particles/particles_unk0/tex_1_img_1.i4.inc.c>
			},
			{
				#include <particles/particles_unk0/tex_1_img_2.i4.inc.c>
			},
		},
	},
	{  /* texture_2 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			8,  /* width */
			8,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk0Txb, texture_2.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][64] */
			{
				#include <particles/particles_unk0/tex_2_img_0.ia8.inc.c>
			},
		},
	},
};
