/*
 * Particle script bank for ParticlesUnk1.
 * ROM: 0xB174A0..0xB176A0 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct particles_unk1Script_0
{
	LBScriptHeader hdr;
	u8             bytecode[11];
} particles_unk1Script_0;

typedef struct particles_unk1Script_1
{
	LBScriptHeader hdr;
	u8             bytecode[122];
} particles_unk1Script_1;

typedef struct particles_unk1Script_2
{
	LBScriptHeader hdr;
	u8             bytecode[30];
} particles_unk1Script_2;

typedef struct particles_unk1Script_3
{
	LBScriptHeader hdr;
	u8             bytecode[122];
} particles_unk1Script_3;

typedef struct particles_unk1Scb
{
	s32              scripts_num;
	u32              script_offsets[4];
	particles_unk1Script_0 script_0;
	particles_unk1Script_1 script_1;
	particles_unk1Script_2 script_2;
	particles_unk1Script_3 script_3;
} particles_unk1Scb;

const particles_unk1Scb dParticlesUnk1Scb = {
	4,
	{
		offsetof(particles_unk1Scb, script_0),
		offsetof(particles_unk1Scb, script_1),
		offsetof(particles_unk1Scb, script_2),
		offsetof(particles_unk1Scb, script_3),
	},
	{  /* script_0 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			0,  /* generator_lifetime */
			1,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			0.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(1),
			lbpMakeGenerator(2),
			lbpWait(2),
			lbpMakeGenerator(3),
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			0,  /* generator_lifetime */
			27,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			1.5f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 60.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-0.2f,  /* update_rate */
			150.0f,  /* size */
		},
		{  /* bytecode */
			lbpAddPosRand,
				LBP_F32(0x42480000) /* 50.0 */,
				LBP_F32(0x41C80000) /* 25.0 */,
				LBP_F32(0x00000000) /* 0.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xBD, 0xFF, 0xF9,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0x1C, 0x36, 0xFF,
			lbpWaitFrame(2, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(3), 0xF3, 0xFF, 0xE1,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(3), 0xFF, 0xC7, 0x1C,
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 2),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xFF, 0xFF, 0x7A,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xDE, 0x7A, 0x00,
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 4),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xFF, 0xEA, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(5), 0xFF, 0x43, 0x05, 0x00,
			lbpWaitFrame(1, 4),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 2),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(8), 0xF3, 0x59, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(9), 0x8F, 0x07, 0x17,
			lbpWaitFrame(1, 4),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 4),
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 5),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0x70, 0x0F, 0x09, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0x3F, 0x03, 0x0A, 0x00,
			lbpWaitFrame(1, 4),
			lbpWaitFrame(2, 5),
			lbpWaitFrame(1, 4),
			lbpWaitFrame(6, 5),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			0,  /* generator_lifetime */
			10,  /* particle_lifetime */
			0,  /* flags */
			2.5f,  /* gravity */
			0.01f,  /* friction */
			{ 0.0f, 50.0f, 0.0f },  /* vel */
			400.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			0.2f,  /* update_rate */
			50.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetPos(LBP_Y), LBP_F32(0x43960000) /* 300.0 */,
			lbpAddPosRand,
				LBP_F32(0x00000000) /* 0.0 */,
				LBP_F32(0x43FA0000) /* 500.0 */,
				LBP_F32(0x00000000) /* 0.0 */,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(11), 0x00,
			lbpSetSizeLerp, LBP_USHORT_S(11), LBP_F32(0x43480000) /* 200.0 */,
			lbpWaitFrame(10, 0),
			lbpEnd(),
		},
	},
	{  /* script_3 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			0,  /* generator_lifetime */
			27,  /* particle_lifetime */
			LBPARTICLE_FLAG_GRAVITY,  /* flags */
			1.5f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 60.0f, 0.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-0.2f,  /* update_rate */
			150.0f,  /* size */
		},
		{  /* bytecode */
			lbpAddPosRand,
				LBP_F32(0x42480000) /* 50.0 */,
				LBP_F32(0x41C80000) /* 25.0 */,
				LBP_F32(0x00000000) /* 0.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xBD, 0xFF, 0xF9,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0x1C, 0x36, 0xFF,
			lbpWaitFrame(2, 4),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(3), 0xF3, 0xFF, 0xE1,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(3), 0xFF, 0xC7, 0x1C,
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 0),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xFF, 0xFF, 0x7A,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xDE, 0x7A, 0x00,
			lbpWaitFrame(1, 4),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 3),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(5), 0xFF, 0xEA, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(5), 0xFF, 0x43, 0x05, 0x00,
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 4),
			lbpWaitFrame(1, 1),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(8), 0xF3, 0x59, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(9), 0x8F, 0x07, 0x17,
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 4),
			lbpWaitFrame(1, 1),
			lbpWaitFrame(1, 2),
			lbpWaitFrame(1, 3),
			lbpWaitFrame(1, 5),
			lbpWaitFrame(1, 1),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0x70, 0x0F, 0x09, 0x00,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B | LBP_A), LBP_USHORT_S(11), 0x3F, 0x03, 0x0A, 0x00,
			lbpWaitFrame(1, 4),
			lbpWaitFrame(2, 1),
			lbpWaitFrame(1, 5),
			lbpWaitFrame(6, 4),
			lbpEnd(),
		},
	},
};
