/*
 * Particle texture bank for ParticlesUnk1.
 * ROM: 0xB176A0..0xB19700 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_txb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <PR/gbi.h>
#include <lb/lbtypes.h>

typedef struct particles_unk1Texture_0
{
	LBTextureHeader hdr;
	u32             data[6];
	u8              image_data[6][1024];
} particles_unk1Texture_0;

typedef struct particles_unk1Texture_1
{
	LBTextureHeader hdr;
	u32             data[2];
	u8              image_data[1][2048];
} particles_unk1Texture_1;

typedef struct particles_unk1Txb
{
	s32              textures_num;
	u32              texture_offsets[2];
	u8               _pad_after_offsets[4];
	particles_unk1Texture_0 texture_0;
	particles_unk1Texture_1 texture_1;
} particles_unk1Txb;

const particles_unk1Txb dParticlesUnk1Txb = {
	2,
	{
		offsetof(particles_unk1Txb, texture_0),
		offsetof(particles_unk1Txb, texture_1),
	},
	{ 0, 0, 0, 0 },  /* _pad_after_offsets */
	{  /* texture_0 */
		{  /* hdr */
			6,  /* count */
			G_IM_FMT_IA,  /* fmt */
			G_IM_SIZ_8b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk1Txb, texture_0.image_data),
			offsetof(particles_unk1Txb, texture_0.image_data[1]),
			offsetof(particles_unk1Txb, texture_0.image_data[2]),
			offsetof(particles_unk1Txb, texture_0.image_data[3]),
			offsetof(particles_unk1Txb, texture_0.image_data[4]),
			offsetof(particles_unk1Txb, texture_0.image_data[5]),
		},
		{  /* image_data[6][1024] */
			{
				#include <particles/particles_unk1/tex_0_img_0.ia8.inc.c>
			},
			{
				#include <particles/particles_unk1/tex_0_img_1.ia8.inc.c>
			},
			{
				#include <particles/particles_unk1/tex_0_img_2.ia8.inc.c>
			},
			{
				#include <particles/particles_unk1/tex_0_img_3.ia8.inc.c>
			},
			{
				#include <particles/particles_unk1/tex_0_img_4.ia8.inc.c>
			},
			{
				#include <particles/particles_unk1/tex_0_img_5.ia8.inc.c>
			},
		},
	},
	{  /* texture_1 */
		{  /* hdr */
			1,  /* count */
			G_IM_FMT_RGBA,  /* fmt */
			G_IM_SIZ_16b,  /* siz */
			32,  /* width */
			32,  /* height */
			1,  /* flags */
		},
		{  /* data[] -- file-relative, baked at compile time */
			offsetof(particles_unk1Txb, texture_1.image_data),
			0  /* trailing pad word, always 0 */,
		},
		{  /* image_data[1][2048] */
			{
				#include <particles/particles_unk1/tex_1_img_0.rgba16.inc.c>
			},
		},
	},
};
