/*
 * Particle script bank for ParticlesUnk2.
 * ROM: 0xB19700..0xB19850 -- see smashbrothers.us.yaml.
 *
 * See [PARTICLE_BANK_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_scb.py; edit by hand thereafter.
 */

#include <ssb_types.h>
#include <stddef.h>
#include <lb/lbtypes.h>
#include <lb/lbparticle_script.h>

typedef struct particles_unk2Script_0
{
	LBScriptHeader hdr;
	u8             bytecode[36];
} particles_unk2Script_0;

typedef struct particles_unk2Script_1
{
	LBScriptHeader hdr;
	u8             bytecode[36];
} particles_unk2Script_1;

typedef struct particles_unk2Script_2
{
	LBScriptHeader hdr;
	u8             bytecode[33];
} particles_unk2Script_2;

typedef struct particles_unk2Script_3
{
	LBScriptHeader hdr;
	u8             bytecode[11];
} particles_unk2Script_3;

typedef struct particles_unk2Scb
{
	s32              scripts_num;
	u32              script_offsets[4];
	particles_unk2Script_0 script_0;
	particles_unk2Script_1 script_1;
	particles_unk2Script_2 script_2;
	particles_unk2Script_3 script_3;
} particles_unk2Scb;

const particles_unk2Scb dParticlesUnk2Scb = {
	4,
	{
		offsetof(particles_unk2Scb, script_0),
		offsetof(particles_unk2Scb, script_1),
		offsetof(particles_unk2Scb, script_2),
		offsetof(particles_unk2Scb, script_3),
	},
	{  /* script_0 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			1,  /* generator_lifetime */
			16,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 1.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			225.0f,  /* size */
		},
		{  /* bytecode */
			lbpSetSizeLerp, LBP_USHORT_S(7), LBP_F32(0x43E10000) /* 450.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0x80, 0xF1,
			lbpWaitFrame(8, 1),
			lbpSetGravity, LBP_F32(0x3DCCCCCD) /* 0.10000000149011612 */,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(9), 0x00,
			lbpSetSizeLerp, LBP_USHORT_S(9), LBP_F32(0x4419C000) /* 615.0 */,
			lbpWaitFrame(8, 1),
			lbpEnd(),
		},
	},
	{  /* script_1 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			1,  /* generator_lifetime */
			16,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 1.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			225.0f,  /* size */
		},
		{  /* bytecode */
			lbpEnvColor(),
			lbpSetSizeLerp, LBP_USHORT_S(7), LBP_F32(0x440E8000) /* 570.0 */,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0x98, 0xFF, 0x61,
			lbpWaitFrame(8, 0),
			lbpSetGravity, LBP_F32(0x3E99999A) /* 0.30000001192092896 */,
			lbpSetPrimBlend(LBP_A), LBP_USHORT_S(9), 0x00,
			lbpSetSizeLerp, LBP_USHORT_S(9), LBP_F32(0x44250000) /* 660.0 */,
			lbpWaitFrame(8, 0),
			lbpEnd(),
		},
	},
	{  /* script_2 */
		{  /* hdr */
			0,  /* kind */
			1,  /* texture_id */
			1,  /* generator_lifetime */
			2,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 1.0f },  /* vel */
			0.0f,  /* unk_0x20 */
			0.0f,  /* unk_0x24 */
			-1.0f,  /* update_rate */
			420.0f,  /* size */
		},
		{  /* bytecode */
			lbpMaskST(),
			lbpSetSizeLerp, LBP_USHORT_S(3), LBP_F32(0x43160000) /* 150.0 */,
			lbpEnvColor(),
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFC, 0x2E,
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFA, 0x9E, 0x00,
			lbpWaitFrame(1, 0),
			lbpSetEnvBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFA, 0x00, 0x42,
			lbpSetPrimBlend(LBP_R | LBP_G | LBP_B), LBP_USHORT_S(1), 0xFF, 0xFF, 0xFF,
			lbpWaitFrame(1, 0),
			lbpEnd(),
		},
	},
	{  /* script_3 */
		{  /* hdr */
			0,  /* kind */
			0,  /* texture_id */
			0,  /* generator_lifetime */
			100,  /* particle_lifetime */
			0,  /* flags */
			1.0f,  /* gravity */
			1.0f,  /* friction */
			{ 0.0f, 0.0f, 1.0f },  /* vel */
			1.0f,  /* unk_0x20 */
			0.01745329238474369f,  /* unk_0x24 */
			1.0f,  /* update_rate */
			0.0f,  /* size */
		},
		{  /* bytecode */
			lbpMakeGenerator(2),
			lbpWait(2),
			lbpMakeGenerator(1),
			lbpMakeGenerator(0),
			lbpEnd(),
		},
	},
};
