#!/usr/bin/env python3
"""Decode a `.sbk` (ALSeqFile) into a hand-editable C source file.

The file is dead simple compared to .ctl:

    ALSeqFile {
        s16 revision;          // 'S1' = 0x5331
        s16 seqCount;
        ALSeqData seqArray[seqCount];
    }
    ALSeqData { u8 *offset; s32 len; }

Each seqArray entry is a (file-relative offset, length) pair. The offset
is patched at load time by alSeqFileNew (src/sys/audio.c). After the
header table, sequences are concatenated in offset order, each followed by
a small (0-3 byte) pad of leftover-from-buffer bytes to align the next
sequence's offset to 4 bytes. We capture those trailing bytes verbatim
into each sequence's u8[] for byte-identical output.

Each sequence's content is itself an ALCMidiHdr (16 trackOffsets + 1
division word) followed by N variable-length compressed-MIDI tracks.
Decompiling that further is a future step; for now we keep each sequence
as a single hex blob.

Run from repo root:
    python3 tools/decode_sbk.py S1_music 0xB277B0 0xB4E5C0 \\
        > src/audio/S1_music_sbk.c
"""
import argparse
import os
import struct
import sys

# Both the extractor and this generator agree on per-sequence filenames
# via the same helper -- otherwise #include paths wouldn't resolve.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _audio_seq_names import suffixes_for_bank


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("name", help="bank name without _sbk suffix (e.g. S1_music)")
    ap.add_argument("rom_lo", type=lambda x: int(x, 0))
    ap.add_argument("rom_hi", type=lambda x: int(x, 0))
    ap.add_argument("--baserom", default="baserom.us.z64")
    args = ap.parse_args()

    with open(args.baserom, "rb") as f:
        f.seek(args.rom_lo)
        data = f.read(args.rom_hi - args.rom_lo)

    rev, n = struct.unpack_from(">hh", data, 0)
    seqs = [struct.unpack_from(">II", data, 4 + i * 8) for i in range(n)]
    # Compute physical_size[i] = next_offset - this_offset (or file_end for last).
    sizes = []
    for i, (off, ln) in enumerate(seqs):
        if i + 1 < n:
            phys = seqs[i + 1][0] - off
        else:
            phys = len(data) - off
        sizes.append(phys)

    sname = args.name.replace(".", "_").replace("-", "_")
    # Match the directory name created by extractMusicSequences.py.
    inc_dir = sname  # e.g. "S1_music"
    banner = "".join(p.capitalize() for p in sname.split("_")) + "Sbk"
    sym_name = "d" + banner

    out = []
    out.append(f"""/*
 * Sequence bank for {args.name}.sbk.
 * ROM: 0x{args.rom_lo:X}..0x{args.rom_hi:X}.
 *
 * See [MUSIC_AND_SFX_DISCOVERIES.md] for the structure of these files.
 * Generated by tools/decode_sbk.py; edit by hand thereafter.
 *
 * The descriptor (revision / seqCount / seqArray) plus every sequence's
 * raw bytes are packed into one aggregate struct; seqArray offsets are
 * resolved with offsetof. Each sequence is a u8[] containing the
 * compressed-MIDI body + any trailing alignment pad bytes (typically
 * leftover-from-buffer data from the bank-builder, captured verbatim).
 */

#include <PR/ultratypes.h>
#include <stddef.h>

typedef struct {{ u32 offset; s32 len; }} SeqEntry;

""")

    out.append(f"typedef struct {banner}\n{{\n")
    out.append(f"\ts16      _revision;\n")
    out.append(f"\ts16      _seqCount;\n")
    out.append(f"\tSeqEntry _seqArray[{n}];\n")
    for i, sz in enumerate(sizes):
        out.append(f"\tu8       seq_{i}[{sz}];\n")
    out.append(f"}} {banner};\n\n")

    out.append(f"const {banner} {sym_name} = {{\n")
    out.append(f"\t0x{rev & 0xFFFF:04X},\n")
    out.append(f"\t{n},\n")
    out.append(f"\t{{\n")
    for i, (off, ln) in enumerate(seqs):
        out.append(f"\t\t{{ offsetof({banner}, seq_{i}), {ln} }},\n")
    out.append(f"\t}},\n")

    suffixes = suffixes_for_bank(args.name, n)
    width = max(2, len(str(n - 1)))
    for i, sz in enumerate(sizes):
        suffix = suffixes[i]
        out.append(f"\t{{  /* seq_{i}{suffix} (logical len {seqs[i][1]}, physical {sz}) */\n")
        out.append(f"\t\t#include <audio/{inc_dir}/seq_{i:0{width}d}{suffix}.cseq.inc.c>\n")
        out.append(f"\t}},\n")
    out.append("};\n")

    sys.stdout.write("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
