#!/usr/bin/env python3
"""Emit the `<bank>_sbk.c` aggregate-struct C source from a manifest
written by extractMusicSequences.py. The output is a build artifact -- the
`.c` file is no longer committed.

Layout matches the original hand-edited file: one outer struct holding
the ALSeqFile header + each sequence's full physical bytes (including
any trailing alignment pad), plus a `const` aggregate initializer with
seqArray entries pointing at the sequence arrays via `offsetof`. Each
sequence body is `#include`'d from its `.cseq.inc.c` so this file stays
small.

Run from repo root (typically invoked by Make):
    python3 tools/gen_sbk_c.py build/src/audio/S1_music.manifest.json \\
        -o build/src/audio/S1_music_sbk.c
"""
import argparse
import json
import os
import sys


def emit(manifest) -> str:
    bank = manifest["bank"]
    rev = manifest["revision"]
    n = manifest["seq_count"]
    width = manifest["name_width"]
    rom_lo = manifest["rom_lo"]
    rom_hi = manifest["rom_hi"]
    seqs = manifest["sequences"]

    # CamelCase from snake_case bank name -> struct name.
    banner = "".join(p.capitalize() for p in bank.split("_")) + "Sbk"
    sym_name = "d" + banner

    out = []
    out.append(f"""/*
 * Sequence bank for {bank}.sbk.
 * ROM: 0x{rom_lo:X}..0x{rom_hi:X}.
 *
 * GENERATED by tools/gen_sbk_c.py from
 * build/src/audio/{bank}.manifest.json -- do not edit by hand.
 *
 * The descriptor (revision / seqCount / seqArray) plus every sequence's
 * raw bytes are packed into one aggregate struct; seqArray offsets are
 * resolved with offsetof. Each sequence is a u8[] containing the
 * compressed-MIDI body + any trailing alignment pad bytes (typically
 * leftover-from-buffer data from the bank-builder, captured verbatim).
 */

#include <PR/ultratypes.h>
#include <stddef.h>

typedef struct {{ u32 offset; s32 len; }} SeqEntry;

""")

    out.append(f"typedef struct {banner}\n{{\n")
    out.append("\ts16      _revision;\n")
    out.append("\ts16      _seqCount;\n")
    out.append(f"\tSeqEntry _seqArray[{n}];\n")
    for s in seqs:
        out.append(f"\tu8       seq_{s['idx']}[{s['physical_len']}];\n")
    out.append(f"}} {banner};\n\n")

    out.append(f"const {banner} {sym_name} = {{\n")
    out.append(f"\t0x{rev:04X},\n")
    out.append(f"\t{n},\n")
    out.append("\t{\n")
    for s in seqs:
        out.append(f"\t\t{{ offsetof({banner}, seq_{s['idx']}), "
                   f"{s['logical_len']} }},\n")
    out.append("\t},\n")

    for s in seqs:
        inc = f"audio/{bank}/seq_{s['idx']:0{width}d}{s['suffix']}.cseq.inc.c"
        out.append(f"\t{{  /* seq_{s['idx']}{s['suffix']} "
                   f"(logical len {s['logical_len']}, "
                   f"physical {s['physical_len']}) */\n")
        out.append(f"\t\t#include <{inc}>\n")
        out.append("\t},\n")
    out.append("};\n")

    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="path to <bank>.manifest.json")
    ap.add_argument("-o", "--output", required=True,
                    help="output .c path (typically build/src/audio/<bank>_sbk.c)")
    args = ap.parse_args()

    with open(args.manifest) as f:
        manifest = json.load(f)

    text = emit(manifest)
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(text)
    print(f"wrote {args.output} ({len(text)} bytes, "
          f"{manifest['seq_count']} sequences)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
