#!/usr/bin/env python3
"""Emit `<bank>_ctl.c` (ALBankFile aggregate) from a manifest written
by [tools/extract_ctl_bank.py](tools/extract_ctl_bank.py). Output mirrors
the legacy `tools/decode_ctl.py` 1:1: same struct typedefs, same field
order, same `offsetof()` initializer layout. Only the comment header
differs.

This is the build artifact; the file is no longer committed.

Run from repo root (typically invoked by Make):
    python3 tools/gen_ctl_c.py build/src/audio/B1_sounds1.manifest.json \\
        -o build/src/audio/B1_sounds1_ctl.c
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import decode_ctl


def emit(manifest) -> str:
    bank = manifest["bank"]
    rom_lo = manifest["rom_lo"]
    rom_hi = manifest["rom_hi"]
    structs = manifest["structs"]
    by_off = decode_ctl.index_by_offset(structs)
    file_struct = by_off[0]

    sname = bank.replace(".", "_").replace("-", "_")
    banner = "".join(p.capitalize() for p in sname.split("_")) + "Ctl"
    sym_name = "d" + banner

    out = []
    out.append(f"""/*
 * Instrument bank for {bank}.ctl.
 * ROM: 0x{rom_lo:X}..0x{rom_hi:X}.
 *
 * GENERATED by tools/gen_ctl_c.py from
 * build/src/audio/{bank}.manifest.json -- do not edit by hand.
 *
 * The file is one ALBankFile aggregate -- header at the front, every
 * reachable ALEnvelope / ALKeyMap / ALSound / ALWaveTable / ALADPCMloop /
 * ALADPCMBook / ALInstrument / ALBank packed in original file-offset
 * order, with internal pointers as offsetof references. The runtime
 * (alBnkfNew + syAudioBnkfPatchBank/Inst/Sound/WaveTable in
 * src/sys/audio.c) walks the tree post-DMA and converts each offset to
 * an absolute pointer. ALWaveTable.base is the only offset that gets the
 * paired .tbl base added rather than the .ctl base.
 */

#include <PR/libaudio.h>
#include <PR/ultratypes.h>
#include <stddef.h>

""")
    decode_ctl.emit_block_typedefs(structs, out)
    decode_ctl.emit_struct(file_struct, structs, banner, out)
    decode_ctl.emit_initializer(structs, by_off, banner, sym_name,
                                 file_struct, out)
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="path to <bank>.manifest.json")
    ap.add_argument("-o", "--output", required=True,
                    help="output .c path (typically build/src/audio/<bank>_ctl.c)")
    args = ap.parse_args()

    with open(args.manifest) as f:
        manifest = json.load(f)
    text = emit(manifest)
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(text)
    print(f"wrote {args.output} ({len(text)} bytes, "
          f"{manifest['wave_count']} waveforms)",
          file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
