#!/usr/bin/python3
"""Verify that --auto chain generation produces byte-identical output to
the current .reloc-driven path.

Strategy: for every reloc .o, extract the raw .data into a scratch file,
patch it via --auto, and compare md5 against the golden binary already
generated by `make RELOC_DATA=1`.

Usage: tools/verifyAutoReloc.py [--version us|jp] [--fid N]
       [--workers W] [--limit M]
"""
import argparse
import concurrent.futures
import hashlib
import os
import subprocess
import sys
import tempfile

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _md5(path):
    h = hashlib.md5()
    with open(path, 'rb') as f:
        for chunk in iter(lambda: f.read(65536), b''):
            h.update(chunk)
    return h.hexdigest()


def _check_file(version, fid):
    o = os.path.join(PROJECT_DIR, 'build', version, 'src', 'relocData', '.build', f'{fid}.o')
    if not os.path.exists(o):
        return (fid, 'no_o', '')
    # Two flavors of golden: .vpk0.bin (compressed-bound files) or .bin
    for ext in ('vpk0.bin', 'bin'):
        gold = os.path.join(PROJECT_DIR, 'build', version, 'assets', version, 'relocData', f'{fid}.{ext}')
        if os.path.exists(gold):
            break
    else:
        return (fid, 'no_gold', '')

    with tempfile.NamedTemporaryFile(suffix='.bin', delete=False) as tmp:
        scratch = tmp.name
    try:
        # Rebuild the raw extract (objcopy with the same TEXTSZ trick as Makefile)
        textsz = subprocess.run(
            ['mips-linux-gnu-objdump', '-h', o],
            capture_output=True, text=True, check=True).stdout
        tsz = 0
        for line in textsz.splitlines():
            parts = line.split()
            if len(parts) >= 3 and parts[1] == '.text':
                tsz = int(parts[2], 16)
                break
        subprocess.run(
            ['mips-linux-gnu-objcopy',
             f'--change-section-lma=.data={tsz}',
             '-O', 'binary',
             '--only-section=.text', '--only-section=.data',
             o, scratch], check=True, capture_output=True)
        # Run fixRelocChain --auto
        r = subprocess.run(
            ['python3', os.path.join(PROJECT_DIR, 'tools', 'fixRelocChain.py'),
             scratch, o, '--auto', '--file-id', str(fid), '--version', version],
            capture_output=True, text=True)
        if r.returncode != 0:
            return (fid, 'auto_fail', r.stderr.strip().splitlines()[-1] if r.stderr else '')
        m1 = _md5(scratch)
        m2 = _md5(gold)
        if m1 == m2:
            return (fid, 'ok', '')
        # Find first differing byte for diagnosis
        with open(scratch, 'rb') as f: a = f.read()
        with open(gold, 'rb') as f: b = f.read()
        if len(a) != len(b):
            return (fid, 'mismatch', f'len {len(a)} vs {len(b)}')
        for i, (x, y) in enumerate(zip(a, b)):
            if x != y:
                return (fid, 'mismatch', f'first_diff @0x{i:X}')
        return (fid, 'mismatch', 'unknown')
    except subprocess.CalledProcessError as e:
        return (fid, 'extract_fail', e.stderr.decode('utf8', 'replace').strip()[:80] if e.stderr else '')
    finally:
        try: os.unlink(scratch)
        except OSError: pass


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--version', default='us', choices=('us', 'jp'))
    ap.add_argument('--fid', type=int, default=None,
                    help='Only test this fid (default: all)')
    ap.add_argument('--workers', type=int, default=8)
    ap.add_argument('--limit', type=int, default=None)
    args = ap.parse_args()

    build_dir = os.path.join(PROJECT_DIR, 'build', args.version, 'src', 'relocData', '.build')
    if not os.path.isdir(build_dir):
        print(f'No build dir: {build_dir}', file=sys.stderr); sys.exit(1)

    fids = []
    if args.fid is not None:
        fids = [args.fid]
    else:
        for f in os.listdir(build_dir):
            if f.endswith('.o'):
                try: fids.append(int(f[:-2]))
                except: pass
        fids.sort()
        if args.limit:
            fids = fids[:args.limit]

    results = []
    with concurrent.futures.ProcessPoolExecutor(max_workers=args.workers) as ex:
        futs = [ex.submit(_check_file, args.version, fid) for fid in fids]
        for fu in concurrent.futures.as_completed(futs):
            results.append(fu.result())

    by_status = {}
    for fid, st, msg in results:
        by_status.setdefault(st, []).append((fid, msg))

    total = len(results)
    ok = len(by_status.get('ok', []))
    mismatch = len(by_status.get('mismatch', []))
    auto_fail = len(by_status.get('auto_fail', []))
    no_gold = len(by_status.get('no_gold', []))
    extract_fail = len(by_status.get('extract_fail', []))
    print(f'\n=== auto-reloc verify (version={args.version}, total={total}) ===')
    print(f'  ok:           {ok}')
    print(f'  mismatch:     {mismatch}')
    print(f'  auto_fail:    {auto_fail}')
    print(f'  no_gold:      {no_gold}')
    print(f'  extract_fail: {extract_fail}')
    if mismatch:
        print('\nSample mismatches (first 10):')
        for fid, msg in sorted(by_status['mismatch'])[:10]:
            print(f'  fid={fid:5d}  {msg}')
    if auto_fail:
        print('\nSample auto_fail (first 10):')
        for fid, msg in sorted(by_status['auto_fail'])[:10]:
            print(f'  fid={fid:5d}  {msg}')

    # Dump full list of mismatch+auto_fail fids to a file so cleanup steps
    # can target them.
    out = os.path.join(PROJECT_DIR, 'build', args.version, 'auto_reloc_bad.txt')
    bad = sorted([fid for fid,_ in by_status.get('mismatch', []) + by_status.get('auto_fail', [])])
    with open(out, 'w') as f:
        for fid in bad: f.write(f'{fid}\n')
    print(f'\nBad-fid list -> {out}')


if __name__ == '__main__':
    main()
