.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel entry
    /* 1000 80000400 3C088004 */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80000404 3C090006 */  lui        $t1, main_BSS_SIZE_HI
    /* 1008 80000408 2508FAD0 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 100C 8000040C 35291EA0 */  ori        $t1, $t1, main_BSS_SIZE_LO
  .L80000410_1010:
    /* 1010 80000410 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1014 80000414 AD000000 */  sw         $zero, 0x0($t0)
    /* 1018 80000418 AD000004 */  sw         $zero, 0x4($t0)
    /* 101C 8000041C 1520FFFC */  bnez       $t1, .L80000410_1010
    /* 1020 80000420 21080008 */   addi      $t0, $t0, 0x8 /* handwritten instruction */
    /* 1024 80000424 3C0A8000 */  lui        $t2, %hi(syMainLoop)
    /* 1028 80000428 3C1D8004 */  lui        $sp, %hi(sSYMainThread1)
    /* 102C 8000042C 254A0870 */  addiu      $t2, $t2, %lo(syMainLoop)
    /* 1030 80000430 01400008 */  jr         $t2
    /* 1034 80000434 27BDFCD0 */   addiu     $sp, $sp, %lo(sSYMainThread1)
    /* 1038 80000438 00000000 */  nop
    /* 103C 8000043C 00000000 */  nop
    /* 1040 80000440 00000000 */  nop
    /* 1044 80000444 00000000 */  nop
    /* 1048 80000448 00000000 */  nop
    /* 104C 8000044C 00000000 */  nop
    /* 1050 80000450 00000000 */  nop
    /* 1054 80000454 00000000 */  nop
    /* 1058 80000458 00000000 */  nop
    /* 105C 8000045C 00000000 */  nop
.size entry, . - entry
