.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osExceptionPreamble
    /* 31870 80030C70 3C1A8003 */  lui        $k0, %hi(__osException) /* handwritten instruction */
    /* 31874 80030C74 275A0C80 */  addiu      $k0, $k0, %lo(__osException) /* handwritten instruction */
    /* 31878 80030C78 03400008 */  jr         $k0
    /* 3187C 80030C7C 00000000 */   nop
.size __osExceptionPreamble, . - __osExceptionPreamble

/* Handwritten function */
glabel __osException
    /* 31880 80030C80 3C1A800A */  lui        $k0, %hi(__osThreadSave) /* handwritten instruction */
    /* 31884 80030C84 275AF040 */  addiu      $k0, $k0, %lo(__osThreadSave) /* handwritten instruction */
    /* 31888 80030C88 FF410020 */  sd         $at, 0x20($k0) /* handwritten instruction */
    /* 3188C 80030C8C 401B6000 */  mfc0       $k1, $12 /* handwritten instruction */
    /* 31890 80030C90 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 31894 80030C94 2401FFFC */  addiu      $at, $zero, -0x4
    /* 31898 80030C98 0361D824 */  and        $k1, $k1, $at
    /* 3189C 80030C9C 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 318A0 80030CA0 FF480058 */  sd         $t0, 0x58($k0) /* handwritten instruction */
    /* 318A4 80030CA4 FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 318A8 80030CA8 FF4A0068 */  sd         $t2, 0x68($k0) /* handwritten instruction */
    /* 318AC 80030CAC AF400018 */  sw         $zero, 0x18($k0) /* handwritten instruction */
    /* 318B0 80030CB0 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 318B4 80030CB4 03404025 */  or         $t0, $k0, $zero
    /* 318B8 80030CB8 3C1A8004 */  lui        $k0, %hi(__osRunningThread) /* handwritten instruction */
    /* 318BC 80030CBC 8F5AD3C0 */  lw         $k0, %lo(__osRunningThread)($k0) /* handwritten instruction */
    /* 318C0 80030CC0 DD090020 */  ld         $t1, 0x20($t0)
    /* 318C4 80030CC4 FF490020 */  sd         $t1, 0x20($k0) /* handwritten instruction */
    /* 318C8 80030CC8 DD090118 */  ld         $t1, 0x118($t0)
    /* 318CC 80030CCC FF490118 */  sd         $t1, 0x118($k0) /* handwritten instruction */
    /* 318D0 80030CD0 DD090058 */  ld         $t1, 0x58($t0)
    /* 318D4 80030CD4 FF490058 */  sd         $t1, 0x58($k0) /* handwritten instruction */
    /* 318D8 80030CD8 DD090060 */  ld         $t1, 0x60($t0)
    /* 318DC 80030CDC FF490060 */  sd         $t1, 0x60($k0) /* handwritten instruction */
    /* 318E0 80030CE0 DD090068 */  ld         $t1, 0x68($t0)
    /* 318E4 80030CE4 FF490068 */  sd         $t1, 0x68($k0) /* handwritten instruction */
    /* 318E8 80030CE8 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 318EC 80030CEC 00004012 */  mflo       $t0
    /* 318F0 80030CF0 FF480108 */  sd         $t0, 0x108($k0) /* handwritten instruction */
    /* 318F4 80030CF4 00004010 */  mfhi       $t0
    /* 318F8 80030CF8 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 318FC 80030CFC FF420028 */  sd         $v0, 0x28($k0) /* handwritten instruction */
    /* 31900 80030D00 FF430030 */  sd         $v1, 0x30($k0) /* handwritten instruction */
    /* 31904 80030D04 FF440038 */  sd         $a0, 0x38($k0) /* handwritten instruction */
    /* 31908 80030D08 FF450040 */  sd         $a1, 0x40($k0) /* handwritten instruction */
    /* 3190C 80030D0C FF460048 */  sd         $a2, 0x48($k0) /* handwritten instruction */
    /* 31910 80030D10 FF470050 */  sd         $a3, 0x50($k0) /* handwritten instruction */
    /* 31914 80030D14 FF4B0070 */  sd         $t3, 0x70($k0) /* handwritten instruction */
    /* 31918 80030D18 FF4C0078 */  sd         $t4, 0x78($k0) /* handwritten instruction */
    /* 3191C 80030D1C FF4D0080 */  sd         $t5, 0x80($k0) /* handwritten instruction */
    /* 31920 80030D20 FF4E0088 */  sd         $t6, 0x88($k0) /* handwritten instruction */
    /* 31924 80030D24 FF4F0090 */  sd         $t7, 0x90($k0) /* handwritten instruction */
    /* 31928 80030D28 FF500098 */  sd         $s0, 0x98($k0) /* handwritten instruction */
    /* 3192C 80030D2C FF5100A0 */  sd         $s1, 0xA0($k0) /* handwritten instruction */
    /* 31930 80030D30 FF5200A8 */  sd         $s2, 0xA8($k0) /* handwritten instruction */
    /* 31934 80030D34 FF5300B0 */  sd         $s3, 0xB0($k0) /* handwritten instruction */
    /* 31938 80030D38 FF5400B8 */  sd         $s4, 0xB8($k0) /* handwritten instruction */
    /* 3193C 80030D3C FF5500C0 */  sd         $s5, 0xC0($k0) /* handwritten instruction */
    /* 31940 80030D40 FF5600C8 */  sd         $s6, 0xC8($k0) /* handwritten instruction */
    /* 31944 80030D44 FF5700D0 */  sd         $s7, 0xD0($k0) /* handwritten instruction */
    /* 31948 80030D48 FF5800D8 */  sd         $t8, 0xD8($k0) /* handwritten instruction */
    /* 3194C 80030D4C FF5900E0 */  sd         $t9, 0xE0($k0) /* handwritten instruction */
    /* 31950 80030D50 FF5C00E8 */  sd         $gp, 0xE8($k0) /* handwritten instruction */
    /* 31954 80030D54 FF5D00F0 */  sd         $sp, 0xF0($k0) /* handwritten instruction */
    /* 31958 80030D58 FF5E00F8 */  sd         $fp, 0xF8($k0) /* handwritten instruction */
    /* 3195C 80030D5C FF5F0100 */  sd         $ra, 0x100($k0) /* handwritten instruction */
    /* 31960 80030D60 11200011 */  beqz       $t1, .L80030DA8_319A8
    /* 31964 80030D64 FF480110 */   sd        $t0, 0x110($k0) /* handwritten instruction */
    /* 31968 80030D68 3C088004 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 3196C 80030D6C 2508D400 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 31970 80030D70 8D080000 */  lw         $t0, 0x0($t0)
    /* 31974 80030D74 2401FFFF */  addiu      $at, $zero, -0x1
    /* 31978 80030D78 01015026 */  xor        $t2, $t0, $at
    /* 3197C 80030D7C 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 31980 80030D80 314AFF00 */  andi       $t2, $t2, 0xFF00
    /* 31984 80030D84 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 31988 80030D88 012A6025 */  or         $t4, $t1, $t2
    /* 3198C 80030D8C 03615824 */  and        $t3, $k1, $at
    /* 31990 80030D90 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 31994 80030D94 016C5825 */  or         $t3, $t3, $t4
    /* 31998 80030D98 01284824 */  and        $t1, $t1, $t0
    /* 3199C 80030D9C 0361D824 */  and        $k1, $k1, $at
    /* 319A0 80030DA0 AF4B0118 */  sw         $t3, 0x118($k0) /* handwritten instruction */
    /* 319A4 80030DA4 0369D825 */  or         $k1, $k1, $t1
  .L80030DA8_319A8:
    /* 319A8 80030DA8 3C09A430 */  lui        $t1, %hi(D_A430000C)
    /* 319AC 80030DAC 8D29000C */  lw         $t1, %lo(D_A430000C)($t1)
    /* 319B0 80030DB0 1120000B */  beqz       $t1, .L80030DE0_319E0
    /* 319B4 80030DB4 00000000 */   nop
    /* 319B8 80030DB8 3C088004 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 319BC 80030DBC 2508D400 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 319C0 80030DC0 8D080000 */  lw         $t0, 0x0($t0)
    /* 319C4 80030DC4 8F4C0128 */  lw         $t4, 0x128($k0) /* handwritten instruction */
    /* 319C8 80030DC8 2401FFFF */  addiu      $at, $zero, -0x1
    /* 319CC 80030DCC 00084402 */  srl        $t0, $t0, 16
    /* 319D0 80030DD0 01014026 */  xor        $t0, $t0, $at
    /* 319D4 80030DD4 3108003F */  andi       $t0, $t0, 0x3F
    /* 319D8 80030DD8 010C4024 */  and        $t0, $t0, $t4
    /* 319DC 80030DDC 01284825 */  or         $t1, $t1, $t0
  .L80030DE0_319E0:
    /* 319E0 80030DE0 AF490128 */  sw         $t1, 0x128($k0) /* handwritten instruction */
    /* 319E4 80030DE4 40087000 */  mfc0       $t0, $14 /* handwritten instruction */
    /* 319E8 80030DE8 AF48011C */  sw         $t0, 0x11C($k0) /* handwritten instruction */
    /* 319EC 80030DEC 8F480018 */  lw         $t0, 0x18($k0) /* handwritten instruction */
    /* 319F0 80030DF0 11000014 */  beqz       $t0, .L80030E44_31A44
    /* 319F4 80030DF4 00000000 */   nop
    /* 319F8 80030DF8 4448F800 */  cfc1       $t0, $31
    /* 319FC 80030DFC 00000000 */  nop
    /* 31A00 80030E00 AF48012C */  sw         $t0, 0x12C($k0) /* handwritten instruction */
    /* 31A04 80030E04 F7400130 */  sdc1       $f0, 0x130($k0)
    /* 31A08 80030E08 F7420138 */  sdc1       $f2, 0x138($k0)
    /* 31A0C 80030E0C F7440140 */  sdc1       $f4, 0x140($k0)
    /* 31A10 80030E10 F7460148 */  sdc1       $f6, 0x148($k0)
    /* 31A14 80030E14 F7480150 */  sdc1       $f8, 0x150($k0)
    /* 31A18 80030E18 F74A0158 */  sdc1       $f10, 0x158($k0)
    /* 31A1C 80030E1C F74C0160 */  sdc1       $f12, 0x160($k0)
    /* 31A20 80030E20 F74E0168 */  sdc1       $f14, 0x168($k0)
    /* 31A24 80030E24 F7500170 */  sdc1       $f16, 0x170($k0)
    /* 31A28 80030E28 F7520178 */  sdc1       $f18, 0x178($k0)
    /* 31A2C 80030E2C F7540180 */  sdc1       $f20, 0x180($k0)
    /* 31A30 80030E30 F7560188 */  sdc1       $f22, 0x188($k0)
    /* 31A34 80030E34 F7580190 */  sdc1       $f24, 0x190($k0)
    /* 31A38 80030E38 F75A0198 */  sdc1       $f26, 0x198($k0)
    /* 31A3C 80030E3C F75C01A0 */  sdc1       $f28, 0x1A0($k0)
    /* 31A40 80030E40 F75E01A8 */  sdc1       $f30, 0x1A8($k0)
  .L80030E44_31A44:
    /* 31A44 80030E44 40086800 */  mfc0       $t0, $13 /* handwritten instruction */
    /* 31A48 80030E48 AF480120 */  sw         $t0, 0x120($k0) /* handwritten instruction */
    /* 31A4C 80030E4C 24090002 */  addiu      $t1, $zero, 0x2
    /* 31A50 80030E50 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 31A54 80030E54 3109007C */  andi       $t1, $t0, 0x7C
    /* 31A58 80030E58 240A0024 */  addiu      $t2, $zero, 0x24
    /* 31A5C 80030E5C 112A00AC */  beq        $t1, $t2, .L80031110_31D10
    /* 31A60 80030E60 00000000 */   nop
    /* 31A64 80030E64 240A002C */  addiu      $t2, $zero, 0x2C
    /* 31A68 80030E68 112A00FB */  beq        $t1, $t2, .L80031258_31E58
    /* 31A6C 80030E6C 00000000 */   nop
    /* 31A70 80030E70 240A0000 */  addiu      $t2, $zero, 0x0
    /* 31A74 80030E74 152A00BF */  bne        $t1, $t2, .L80031174_31D74
    /* 31A78 80030E78 00000000 */   nop
    /* 31A7C 80030E7C 03688024 */  and        $s0, $k1, $t0
  .L80030E80_31A80:
    /* 31A80 80030E80 3209FF00 */  andi       $t1, $s0, 0xFF00
    /* 31A84 80030E84 00095302 */  srl        $t2, $t1, 12
    /* 31A88 80030E88 15400003 */  bnez       $t2, .L80030E98_31A98
    /* 31A8C 80030E8C 00000000 */   nop
    /* 31A90 80030E90 00095202 */  srl        $t2, $t1, 8
    /* 31A94 80030E94 214A0010 */  addi       $t2, $t2, 0x10 /* handwritten instruction */
  .L80030E98_31A98:
    /* 31A98 80030E98 3C018004 */  lui        $at, %hi(__osIntOffTable)
    /* 31A9C 80030E9C 002A0821 */  addu       $at, $at, $t2
    /* 31AA0 80030EA0 902AF1B0 */  lbu        $t2, %lo(__osIntOffTable)($at)
    /* 31AA4 80030EA4 3C018004 */  lui        $at, %hi(__osIntTable)
    /* 31AA8 80030EA8 002A0821 */  addu       $at, $at, $t2
    /* 31AAC 80030EAC 8C2AF1D0 */  lw         $t2, %lo(__osIntTable)($at)
    /* 31AB0 80030EB0 01400008 */  jr         $t2
    /* 31AB4 80030EB4 00000000 */   nop
  jlabel .L80030EB8_31AB8
    /* 31AB8 80030EB8 2401DFFF */  addiu      $at, $zero, -0x2001
    /* 31ABC 80030EBC 1000FFF0 */  b          .L80030E80_31A80
    /* 31AC0 80030EC0 02018024 */   and       $s0, $s0, $at
  jlabel .L80030EC4_31AC4
    /* 31AC4 80030EC4 2401BFFF */  addiu      $at, $zero, -0x4001
    /* 31AC8 80030EC8 1000FFED */  b          .L80030E80_31A80
    /* 31ACC 80030ECC 02018024 */   and       $s0, $s0, $at
  jlabel .L80030ED0_31AD0
    /* 31AD0 80030ED0 40095800 */  mfc0       $t1, $11 /* handwritten instruction */
    /* 31AD4 80030ED4 40895800 */  mtc0       $t1, $11 /* handwritten instruction */
    /* 31AD8 80030ED8 0C00C469 */  jal        send_mesg
    /* 31ADC 80030EDC 24040018 */   addiu     $a0, $zero, 0x18
    /* 31AE0 80030EE0 3C01FFFF */  lui        $at, (0xFFFF7FFF >> 16)
    /* 31AE4 80030EE4 34217FFF */  ori        $at, $at, (0xFFFF7FFF & 0xFFFF)
    /* 31AE8 80030EE8 1000FFE5 */  b          .L80030E80_31A80
    /* 31AEC 80030EEC 02018024 */   and       $s0, $s0, $at
  jlabel .L80030EF0_31AF0
    /* 31AF0 80030EF0 3C098004 */  lui        $t1, %hi(__osHwIntTable)
    /* 31AF4 80030EF4 2529D380 */  addiu      $t1, $t1, %lo(__osHwIntTable)
    /* 31AF8 80030EF8 8D2A0008 */  lw         $t2, 0x8($t1)
    /* 31AFC 80030EFC 2401F7FF */  addiu      $at, $zero, -0x801
    /* 31B00 80030F00 02018024 */  and        $s0, $s0, $at
    /* 31B04 80030F04 11400007 */  beqz       $t2, .L80030F24_31B24
    /* 31B08 80030F08 21290008 */   addi      $t1, $t1, 0x8 /* handwritten instruction */
    /* 31B0C 80030F0C 0140F809 */  jalr       $t2
    /* 31B10 80030F10 8D3D0004 */   lw        $sp, 0x4($t1)
    /* 31B14 80030F14 10400003 */  beqz       $v0, .L80030F24_31B24
    /* 31B18 80030F18 24040010 */   addiu     $a0, $zero, 0x10
    /* 31B1C 80030F1C 10000082 */  b          .L80031128_31D28
    /* 31B20 80030F20 00000000 */   nop
  .L80030F24_31B24:
    /* 31B24 80030F24 0C00C469 */  jal        send_mesg
    /* 31B28 80030F28 00000000 */   nop
    /* 31B2C 80030F2C 1000FFD4 */  b          .L80030E80_31A80
    /* 31B30 80030F30 00000000 */   nop
  jlabel .L80030F34_31B34
    /* 31B34 80030F34 3C088004 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 31B38 80030F38 2508D400 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 31B3C 80030F3C 8D080000 */  lw         $t0, 0x0($t0)
    /* 31B40 80030F40 3C11A430 */  lui        $s1, %hi(D_A4300008)
    /* 31B44 80030F44 8E310008 */  lw         $s1, %lo(D_A4300008)($s1)
    /* 31B48 80030F48 00084402 */  srl        $t0, $t0, 16
    /* 31B4C 80030F4C 02288824 */  and        $s1, $s1, $t0
    /* 31B50 80030F50 32290001 */  andi       $t1, $s1, 0x1
    /* 31B54 80030F54 11200013 */  beqz       $t1, .L80030FA4_31BA4
    /* 31B58 80030F58 00000000 */   nop
    /* 31B5C 80030F5C 3C0CA404 */  lui        $t4, %hi(D_A4040010)
    /* 31B60 80030F60 8D8C0010 */  lw         $t4, %lo(D_A4040010)($t4)
    /* 31B64 80030F64 34098008 */  ori        $t1, $zero, 0x8008
    /* 31B68 80030F68 3C01A404 */  lui        $at, %hi(D_A4040010)
    /* 31B6C 80030F6C 318C0300 */  andi       $t4, $t4, 0x300
    /* 31B70 80030F70 3231003E */  andi       $s1, $s1, 0x3E
    /* 31B74 80030F74 11800007 */  beqz       $t4, .L80030F94_31B94
    /* 31B78 80030F78 AC290010 */   sw        $t1, %lo(D_A4040010)($at)
    /* 31B7C 80030F7C 0C00C469 */  jal        send_mesg
    /* 31B80 80030F80 24040020 */   addiu     $a0, $zero, 0x20
    /* 31B84 80030F84 12200038 */  beqz       $s1, .L80031068_31C68
    /* 31B88 80030F88 00000000 */   nop
    /* 31B8C 80030F8C 10000005 */  b          .L80030FA4_31BA4
    /* 31B90 80030F90 00000000 */   nop
  .L80030F94_31B94:
    /* 31B94 80030F94 0C00C469 */  jal        send_mesg
    /* 31B98 80030F98 24040058 */   addiu     $a0, $zero, 0x58
    /* 31B9C 80030F9C 12200032 */  beqz       $s1, .L80031068_31C68
    /* 31BA0 80030FA0 00000000 */   nop
  .L80030FA4_31BA4:
    /* 31BA4 80030FA4 32290008 */  andi       $t1, $s1, 0x8
    /* 31BA8 80030FA8 11200007 */  beqz       $t1, .L80030FC8_31BC8
    /* 31BAC 80030FAC 3C01A440 */   lui       $at, %hi(D_A4400010)
    /* 31BB0 80030FB0 32310037 */  andi       $s1, $s1, 0x37
    /* 31BB4 80030FB4 AC200010 */  sw         $zero, %lo(D_A4400010)($at)
    /* 31BB8 80030FB8 0C00C469 */  jal        send_mesg
    /* 31BBC 80030FBC 24040038 */   addiu     $a0, $zero, 0x38
    /* 31BC0 80030FC0 12200029 */  beqz       $s1, .L80031068_31C68
    /* 31BC4 80030FC4 00000000 */   nop
  .L80030FC8_31BC8:
    /* 31BC8 80030FC8 32290004 */  andi       $t1, $s1, 0x4
    /* 31BCC 80030FCC 11200009 */  beqz       $t1, .L80030FF4_31BF4
    /* 31BD0 80030FD0 00000000 */   nop
    /* 31BD4 80030FD4 24090001 */  addiu      $t1, $zero, 0x1
    /* 31BD8 80030FD8 3C01A450 */  lui        $at, %hi(D_A450000C)
    /* 31BDC 80030FDC 3231003B */  andi       $s1, $s1, 0x3B
    /* 31BE0 80030FE0 AC29000C */  sw         $t1, %lo(D_A450000C)($at)
    /* 31BE4 80030FE4 0C00C469 */  jal        send_mesg
    /* 31BE8 80030FE8 24040030 */   addiu     $a0, $zero, 0x30
    /* 31BEC 80030FEC 1220001E */  beqz       $s1, .L80031068_31C68
    /* 31BF0 80030FF0 00000000 */   nop
  .L80030FF4_31BF4:
    /* 31BF4 80030FF4 32290002 */  andi       $t1, $s1, 0x2
    /* 31BF8 80030FF8 11200007 */  beqz       $t1, .L80031018_31C18
    /* 31BFC 80030FFC 3C01A480 */   lui       $at, %hi(D_A4800018)
    /* 31C00 80031000 3231003D */  andi       $s1, $s1, 0x3D
    /* 31C04 80031004 AC200018 */  sw         $zero, %lo(D_A4800018)($at)
    /* 31C08 80031008 0C00C469 */  jal        send_mesg
    /* 31C0C 8003100C 24040028 */   addiu     $a0, $zero, 0x28
    /* 31C10 80031010 12200015 */  beqz       $s1, .L80031068_31C68
    /* 31C14 80031014 00000000 */   nop
  .L80031018_31C18:
    /* 31C18 80031018 32290010 */  andi       $t1, $s1, 0x10
    /* 31C1C 8003101C 11200009 */  beqz       $t1, .L80031044_31C44
    /* 31C20 80031020 00000000 */   nop
    /* 31C24 80031024 24090002 */  addiu      $t1, $zero, 0x2
    /* 31C28 80031028 3C01A460 */  lui        $at, %hi(D_A4600010)
    /* 31C2C 8003102C 3231002F */  andi       $s1, $s1, 0x2F
    /* 31C30 80031030 AC290010 */  sw         $t1, %lo(D_A4600010)($at)
    /* 31C34 80031034 0C00C469 */  jal        send_mesg
    /* 31C38 80031038 24040040 */   addiu     $a0, $zero, 0x40
    /* 31C3C 8003103C 1220000A */  beqz       $s1, .L80031068_31C68
    /* 31C40 80031040 00000000 */   nop
  .L80031044_31C44:
    /* 31C44 80031044 32290020 */  andi       $t1, $s1, 0x20
    /* 31C48 80031048 11200007 */  beqz       $t1, .L80031068_31C68
    /* 31C4C 8003104C 00000000 */   nop
    /* 31C50 80031050 24090800 */  addiu      $t1, $zero, 0x800
    /* 31C54 80031054 3C01A430 */  lui        $at, %hi(D_A4300000)
    /* 31C58 80031058 3231001F */  andi       $s1, $s1, 0x1F
    /* 31C5C 8003105C AC290000 */  sw         $t1, %lo(D_A4300000)($at)
    /* 31C60 80031060 0C00C469 */  jal        send_mesg
    /* 31C64 80031064 24040048 */   addiu     $a0, $zero, 0x48
  .L80031068_31C68:
    /* 31C68 80031068 2401FBFF */  addiu      $at, $zero, -0x401
    /* 31C6C 8003106C 1000FF84 */  b          .L80030E80_31A80
    /* 31C70 80031070 02018024 */   and       $s0, $s0, $at
  jlabel .L80031074_31C74
    /* 31C74 80031074 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 31C78 80031078 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 31C7C 8003107C 3C098004 */  lui        $t1, %hi(__osShutdown)
    /* 31C80 80031080 0361D824 */  and        $k1, $k1, $at
    /* 31C84 80031084 AF5B0118 */  sw         $k1, 0x118($k0) /* handwritten instruction */
    /* 31C88 80031088 2529D3FC */  addiu      $t1, $t1, %lo(__osShutdown)
    /* 31C8C 8003108C 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 31C90 80031090 11400003 */  beqz       $t2, .L800310A0_31CA0
    /* 31C94 80031094 2401EFFF */   addiu     $at, $zero, -0x1001
    /* 31C98 80031098 10000023 */  b          .L80031128_31D28
    /* 31C9C 8003109C 02018024 */   and       $s0, $s0, $at
  .L800310A0_31CA0:
    /* 31CA0 800310A0 240A0001 */  addiu      $t2, $zero, 0x1
    /* 31CA4 800310A4 AD2A0000 */  sw         $t2, 0x0($t1)
    /* 31CA8 800310A8 0C00C469 */  jal        send_mesg
    /* 31CAC 800310AC 24040070 */   addiu     $a0, $zero, 0x70
    /* 31CB0 800310B0 3C0A8004 */  lui        $t2, %hi(__osRunQueue)
    /* 31CB4 800310B4 8D4AD3B8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 31CB8 800310B8 2401EFFF */  addiu      $at, $zero, -0x1001
    /* 31CBC 800310BC 02018024 */  and        $s0, $s0, $at
    /* 31CC0 800310C0 8D5B0118 */  lw         $k1, 0x118($t2) /* handwritten instruction */
    /* 31CC4 800310C4 0361D824 */  and        $k1, $k1, $at
    /* 31CC8 800310C8 10000017 */  b          .L80031128_31D28
    /* 31CCC 800310CC AD5B0118 */   sw        $k1, 0x118($t2) /* handwritten instruction */
  jlabel .L800310D0_31CD0
    /* 31CD0 800310D0 2401FDFF */  addiu      $at, $zero, -0x201
    /* 31CD4 800310D4 01014024 */  and        $t0, $t0, $at
    /* 31CD8 800310D8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 31CDC 800310DC 0C00C469 */  jal        send_mesg
    /* 31CE0 800310E0 24040008 */   addiu     $a0, $zero, 0x8
    /* 31CE4 800310E4 2401FDFF */  addiu      $at, $zero, -0x201
    /* 31CE8 800310E8 1000FF65 */  b          .L80030E80_31A80
    /* 31CEC 800310EC 02018024 */   and       $s0, $s0, $at
  jlabel .L800310F0_31CF0
    /* 31CF0 800310F0 2401FEFF */  addiu      $at, $zero, -0x101
    /* 31CF4 800310F4 01014024 */  and        $t0, $t0, $at
    /* 31CF8 800310F8 40886800 */  mtc0       $t0, $13 /* handwritten instruction */
    /* 31CFC 800310FC 0C00C469 */  jal        send_mesg
    /* 31D00 80031100 24040000 */   addiu     $a0, $zero, 0x0
    /* 31D04 80031104 2401FEFF */  addiu      $at, $zero, -0x101
    /* 31D08 80031108 1000FF5D */  b          .L80030E80_31A80
    /* 31D0C 8003110C 02018024 */   and       $s0, $s0, $at
  .L80031110_31D10:
    /* 31D10 80031110 24090001 */  addiu      $t1, $zero, 0x1
    /* 31D14 80031114 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 31D18 80031118 0C00C469 */  jal        send_mesg
    /* 31D1C 8003111C 24040050 */   addiu     $a0, $zero, 0x50
    /* 31D20 80031120 10000001 */  b          .L80031128_31D28
    /* 31D24 80031124 00000000 */   nop
  jlabel .L80031128_31D28
    /* 31D28 80031128 3C0A8004 */  lui        $t2, %hi(__osRunQueue)
    /* 31D2C 8003112C 8D4AD3B8 */  lw         $t2, %lo(__osRunQueue)($t2)
    /* 31D30 80031130 8F490004 */  lw         $t1, 0x4($k0) /* handwritten instruction */
    /* 31D34 80031134 8D4B0004 */  lw         $t3, 0x4($t2)
    /* 31D38 80031138 012B082A */  slt        $at, $t1, $t3
    /* 31D3C 8003113C 10200007 */  beqz       $at, .L8003115C_31D5C
    /* 31D40 80031140 00000000 */   nop
    /* 31D44 80031144 3C048004 */  lui        $a0, %hi(__osRunQueue)
    /* 31D48 80031148 03402825 */  or         $a1, $k0, $zero
    /* 31D4C 8003114C 0C00C4E3 */  jal        __osEnqueueThread
    /* 31D50 80031150 2484D3B8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 31D54 80031154 0800C4F9 */  j          __osDispatchThread
    /* 31D58 80031158 00000000 */   nop
  .L8003115C_31D5C:
    /* 31D5C 8003115C 3C098004 */  lui        $t1, %hi(__osRunQueue)
    /* 31D60 80031160 2529D3B8 */  addiu      $t1, $t1, %lo(__osRunQueue)
    /* 31D64 80031164 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 31D68 80031168 AF4A0000 */  sw         $t2, 0x0($k0) /* handwritten instruction */
    /* 31D6C 8003116C 0800C4F9 */  j          __osDispatchThread
    /* 31D70 80031170 AD3A0000 */   sw        $k0, 0x0($t1) /* handwritten instruction */
  .L80031174_31D74:
    /* 31D74 80031174 3C018004 */  lui        $at, %hi(__osFaultedThread)
    /* 31D78 80031178 AC3AD3C4 */  sw         $k0, %lo(__osFaultedThread)($at) /* handwritten instruction */
    /* 31D7C 8003117C 24090001 */  addiu      $t1, $zero, 0x1
    /* 31D80 80031180 A7490010 */  sh         $t1, 0x10($k0) /* handwritten instruction */
    /* 31D84 80031184 24090002 */  addiu      $t1, $zero, 0x2
    /* 31D88 80031188 A7490012 */  sh         $t1, 0x12($k0) /* handwritten instruction */
    /* 31D8C 8003118C 400A4000 */  mfc0       $t2, $8 /* handwritten instruction */
    /* 31D90 80031190 AF4A0124 */  sw         $t2, 0x124($k0) /* handwritten instruction */
    /* 31D94 80031194 0C00C469 */  jal        send_mesg
    /* 31D98 80031198 24040060 */   addiu     $a0, $zero, 0x60
    /* 31D9C 8003119C 0800C4F9 */  j          __osDispatchThread
    /* 31DA0 800311A0 00000000 */   nop
.size __osException, . - __osException

/* Handwritten function */
glabel send_mesg
    /* 31DA4 800311A4 3C0A800A */  lui        $t2, %hi(__osEventStateTab)
    /* 31DA8 800311A8 254A04D0 */  addiu      $t2, $t2, %lo(__osEventStateTab)
    /* 31DAC 800311AC 01445021 */  addu       $t2, $t2, $a0
    /* 31DB0 800311B0 8D490000 */  lw         $t1, 0x0($t2)
    /* 31DB4 800311B4 03E09025 */  or         $s2, $ra, $zero
    /* 31DB8 800311B8 11200025 */  beqz       $t1, .L80031250_31E50
    /* 31DBC 800311BC 00000000 */   nop
    /* 31DC0 800311C0 8D2B0008 */  lw         $t3, 0x8($t1)
    /* 31DC4 800311C4 8D2C0010 */  lw         $t4, 0x10($t1)
    /* 31DC8 800311C8 016C082A */  slt        $at, $t3, $t4
    /* 31DCC 800311CC 10200020 */  beqz       $at, .L80031250_31E50
    /* 31DD0 800311D0 00000000 */   nop
    /* 31DD4 800311D4 8D2D000C */  lw         $t5, 0xC($t1)
    /* 31DD8 800311D8 01AB6821 */  addu       $t5, $t5, $t3
    /* 31DDC 800311DC 01AC001A */  div        $zero, $t5, $t4
    /* 31DE0 800311E0 15800002 */  bnez       $t4, .L800311EC_31DEC
    /* 31DE4 800311E4 00000000 */   nop
    /* 31DE8 800311E8 0007000D */  break      7
  .L800311EC_31DEC:
    /* 31DEC 800311EC 2401FFFF */  addiu      $at, $zero, -0x1
    /* 31DF0 800311F0 15810004 */  bne        $t4, $at, .L80031204_31E04
    /* 31DF4 800311F4 3C018000 */   lui       $at, (0x80000000 >> 16)
    /* 31DF8 800311F8 15A10002 */  bne        $t5, $at, .L80031204_31E04
    /* 31DFC 800311FC 00000000 */   nop
    /* 31E00 80031200 0006000D */  break      6
  .L80031204_31E04:
    /* 31E04 80031204 8D2C0014 */  lw         $t4, 0x14($t1)
    /* 31E08 80031208 00006810 */  mfhi       $t5
    /* 31E0C 8003120C 000D6880 */  sll        $t5, $t5, 2
    /* 31E10 80031210 018D6021 */  addu       $t4, $t4, $t5
    /* 31E14 80031214 8D4D0004 */  lw         $t5, 0x4($t2)
    /* 31E18 80031218 256A0001 */  addiu      $t2, $t3, 0x1
    /* 31E1C 8003121C AD8D0000 */  sw         $t5, 0x0($t4)
    /* 31E20 80031220 AD2A0008 */  sw         $t2, 0x8($t1)
    /* 31E24 80031224 8D2A0000 */  lw         $t2, 0x0($t1)
    /* 31E28 80031228 8D4B0000 */  lw         $t3, 0x0($t2)
    /* 31E2C 8003122C 11600008 */  beqz       $t3, .L80031250_31E50
    /* 31E30 80031230 00000000 */   nop
    /* 31E34 80031234 0C00C4F5 */  jal        __osPopThread
    /* 31E38 80031238 01202025 */   or        $a0, $t1, $zero
    /* 31E3C 8003123C 00405025 */  or         $t2, $v0, $zero
    /* 31E40 80031240 3C048004 */  lui        $a0, %hi(__osRunQueue)
    /* 31E44 80031244 01402825 */  or         $a1, $t2, $zero
    /* 31E48 80031248 0C00C4E3 */  jal        __osEnqueueThread
    /* 31E4C 8003124C 2484D3B8 */   addiu     $a0, $a0, %lo(__osRunQueue)
  .L80031250_31E50:
    /* 31E50 80031250 02400008 */  jr         $s2
    /* 31E54 80031254 00000000 */   nop
  .L80031258_31E58:
    /* 31E58 80031258 3C013000 */  lui        $at, (0x30000000 >> 16)
    /* 31E5C 8003125C 01014824 */  and        $t1, $t0, $at
    /* 31E60 80031260 00094F02 */  srl        $t1, $t1, 28
    /* 31E64 80031264 240A0001 */  addiu      $t2, $zero, 0x1
    /* 31E68 80031268 152AFFC2 */  bne        $t1, $t2, .L80031174_31D74
    /* 31E6C 8003126C 00000000 */   nop
    /* 31E70 80031270 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 31E74 80031274 3C012000 */  lui        $at, (0x20000000 >> 16)
    /* 31E78 80031278 24090001 */  addiu      $t1, $zero, 0x1
    /* 31E7C 8003127C 0361D825 */  or         $k1, $k1, $at
    /* 31E80 80031280 AF490018 */  sw         $t1, 0x18($k0) /* handwritten instruction */
    /* 31E84 80031284 1000FFB5 */  b          .L8003115C_31D5C
    /* 31E88 80031288 AF5B0118 */   sw        $k1, 0x118($k0) /* handwritten instruction */
.size send_mesg, . - send_mesg

/* Handwritten function */
glabel __osEnqueueAndYield
    /* 31E8C 8003128C 3C058004 */  lui        $a1, %hi(__osRunningThread)
    /* 31E90 80031290 8CA5D3C0 */  lw         $a1, %lo(__osRunningThread)($a1)
    /* 31E94 80031294 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 31E98 80031298 8CBB0018 */  lw         $k1, 0x18($a1) /* handwritten instruction */
    /* 31E9C 8003129C 35080002 */  ori        $t0, $t0, 0x2
    /* 31EA0 800312A0 ACA80118 */  sw         $t0, 0x118($a1)
    /* 31EA4 800312A4 FCB00098 */  sd         $s0, 0x98($a1)
    /* 31EA8 800312A8 FCB100A0 */  sd         $s1, 0xA0($a1)
    /* 31EAC 800312AC FCB200A8 */  sd         $s2, 0xA8($a1)
    /* 31EB0 800312B0 FCB300B0 */  sd         $s3, 0xB0($a1)
    /* 31EB4 800312B4 FCB400B8 */  sd         $s4, 0xB8($a1)
    /* 31EB8 800312B8 FCB500C0 */  sd         $s5, 0xC0($a1)
    /* 31EBC 800312BC FCB600C8 */  sd         $s6, 0xC8($a1)
    /* 31EC0 800312C0 FCB700D0 */  sd         $s7, 0xD0($a1)
    /* 31EC4 800312C4 FCBC00E8 */  sd         $gp, 0xE8($a1)
    /* 31EC8 800312C8 FCBD00F0 */  sd         $sp, 0xF0($a1)
    /* 31ECC 800312CC FCBE00F8 */  sd         $fp, 0xF8($a1)
    /* 31ED0 800312D0 FCBF0100 */  sd         $ra, 0x100($a1)
    /* 31ED4 800312D4 13600009 */  beqz       $k1, .L800312FC_31EFC /* handwritten instruction */
    /* 31ED8 800312D8 ACBF011C */   sw        $ra, 0x11C($a1)
    /* 31EDC 800312DC 445BF800 */  cfc1       $k1, $31
    /* 31EE0 800312E0 F4B40180 */  sdc1       $f20, 0x180($a1)
    /* 31EE4 800312E4 F4B60188 */  sdc1       $f22, 0x188($a1)
    /* 31EE8 800312E8 F4B80190 */  sdc1       $f24, 0x190($a1)
    /* 31EEC 800312EC F4BA0198 */  sdc1       $f26, 0x198($a1)
    /* 31EF0 800312F0 F4BC01A0 */  sdc1       $f28, 0x1A0($a1)
    /* 31EF4 800312F4 F4BE01A8 */  sdc1       $f30, 0x1A8($a1)
    /* 31EF8 800312F8 ACBB012C */  sw         $k1, 0x12C($a1) /* handwritten instruction */
  .L800312FC_31EFC:
    /* 31EFC 800312FC 8CBB0118 */  lw         $k1, 0x118($a1) /* handwritten instruction */
    /* 31F00 80031300 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 31F04 80031304 1120000D */  beqz       $t1, .L8003133C_31F3C
    /* 31F08 80031308 00000000 */   nop
    /* 31F0C 8003130C 3C088004 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 31F10 80031310 2508D400 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 31F14 80031314 8D080000 */  lw         $t0, 0x0($t0)
    /* 31F18 80031318 2401FFFF */  addiu      $at, $zero, -0x1
    /* 31F1C 8003131C 01014026 */  xor        $t0, $t0, $at
    /* 31F20 80031320 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 31F24 80031324 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 31F28 80031328 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 31F2C 8003132C 01284825 */  or         $t1, $t1, $t0
    /* 31F30 80031330 0361D824 */  and        $k1, $k1, $at
    /* 31F34 80031334 0369D825 */  or         $k1, $k1, $t1
    /* 31F38 80031338 ACBB0118 */  sw         $k1, 0x118($a1) /* handwritten instruction */
  .L8003133C_31F3C:
    /* 31F3C 8003133C 3C1BA430 */  lui        $k1, %hi(D_A430000C) /* handwritten instruction */
    /* 31F40 80031340 8F7B000C */  lw         $k1, %lo(D_A430000C)($k1) /* handwritten instruction */
    /* 31F44 80031344 1360000B */  beqz       $k1, .L80031374_31F74 /* handwritten instruction */
    /* 31F48 80031348 00000000 */   nop
    /* 31F4C 8003134C 3C1A8004 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 31F50 80031350 275AD400 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 31F54 80031354 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 31F58 80031358 8CA80128 */  lw         $t0, 0x128($a1)
    /* 31F5C 8003135C 2401FFFF */  addiu      $at, $zero, -0x1
    /* 31F60 80031360 001AD402 */  srl        $k0, $k0, 16
    /* 31F64 80031364 0341D026 */  xor        $k0, $k0, $at
    /* 31F68 80031368 335A003F */  andi       $k0, $k0, 0x3F /* handwritten instruction */
    /* 31F6C 8003136C 0348D024 */  and        $k0, $k0, $t0
    /* 31F70 80031370 037AD825 */  or         $k1, $k1, $k0
  .L80031374_31F74:
    /* 31F74 80031374 10800003 */  beqz       $a0, .L80031384_31F84
    /* 31F78 80031378 ACBB0128 */   sw        $k1, 0x128($a1) /* handwritten instruction */
    /* 31F7C 8003137C 0C00C4E3 */  jal        __osEnqueueThread
    /* 31F80 80031380 00000000 */   nop
  .L80031384_31F84:
    /* 31F84 80031384 0800C4F9 */  j          __osDispatchThread
    /* 31F88 80031388 00000000 */   nop
.size __osEnqueueAndYield, . - __osEnqueueAndYield

glabel __osEnqueueThread
    /* 31F8C 8003138C 8C980000 */  lw         $t8, 0x0($a0)
    /* 31F90 80031390 8CAF0004 */  lw         $t7, 0x4($a1)
    /* 31F94 80031394 0080C825 */  or         $t9, $a0, $zero
    /* 31F98 80031398 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 31F9C 8003139C 01CF082A */  slt        $at, $t6, $t7
    /* 31FA0 800313A0 14200007 */  bnez       $at, .L800313C0_31FC0
    /* 31FA4 800313A4 00000000 */   nop
  .L800313A8_31FA8:
    /* 31FA8 800313A8 0300C825 */  or         $t9, $t8, $zero
    /* 31FAC 800313AC 8F180000 */  lw         $t8, 0x0($t8)
    /* 31FB0 800313B0 8F0E0004 */  lw         $t6, 0x4($t8)
    /* 31FB4 800313B4 01CF082A */  slt        $at, $t6, $t7
    /* 31FB8 800313B8 1020FFFB */  beqz       $at, .L800313A8_31FA8
    /* 31FBC 800313BC 00000000 */   nop
  .L800313C0_31FC0:
    /* 31FC0 800313C0 8F380000 */  lw         $t8, 0x0($t9)
    /* 31FC4 800313C4 ACB80000 */  sw         $t8, 0x0($a1)
    /* 31FC8 800313C8 AF250000 */  sw         $a1, 0x0($t9)
    /* 31FCC 800313CC 03E00008 */  jr         $ra
    /* 31FD0 800313D0 ACA40008 */   sw        $a0, 0x8($a1)
.size __osEnqueueThread, . - __osEnqueueThread

glabel __osPopThread
    /* 31FD4 800313D4 8C820000 */  lw         $v0, 0x0($a0)
    /* 31FD8 800313D8 8C590000 */  lw         $t9, 0x0($v0)
    /* 31FDC 800313DC 03E00008 */  jr         $ra
    /* 31FE0 800313E0 AC990000 */   sw        $t9, 0x0($a0)
.size __osPopThread, . - __osPopThread

/* Handwritten function */
glabel __osDispatchThread
    /* 31FE4 800313E4 3C048004 */  lui        $a0, %hi(__osRunQueue)
    /* 31FE8 800313E8 0C00C4F5 */  jal        __osPopThread
    /* 31FEC 800313EC 2484D3B8 */   addiu     $a0, $a0, %lo(__osRunQueue)
    /* 31FF0 800313F0 3C018004 */  lui        $at, %hi(__osRunningThread)
    /* 31FF4 800313F4 AC22D3C0 */  sw         $v0, %lo(__osRunningThread)($at)
    /* 31FF8 800313F8 24080004 */  addiu      $t0, $zero, 0x4
    /* 31FFC 800313FC A4480010 */  sh         $t0, 0x10($v0)
    /* 32000 80031400 0040D025 */  or         $k0, $v0, $zero
    /* 32004 80031404 3C088004 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 32008 80031408 8F5B0118 */  lw         $k1, 0x118($k0) /* handwritten instruction */
    /* 3200C 8003140C 2508D400 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 32010 80031410 8D080000 */  lw         $t0, 0x0($t0)
    /* 32014 80031414 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 32018 80031418 3369FF00 */  andi       $t1, $k1, 0xFF00 /* handwritten instruction */
    /* 3201C 8003141C 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 32020 80031420 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 32024 80031424 01284824 */  and        $t1, $t1, $t0
    /* 32028 80031428 0361D824 */  and        $k1, $k1, $at
    /* 3202C 8003142C 0369D825 */  or         $k1, $k1, $t1
    /* 32030 80031430 409B6000 */  mtc0       $k1, $12 /* handwritten instruction */
    /* 32034 80031434 DF5B0108 */  ld         $k1, 0x108($k0) /* handwritten instruction */
    /* 32038 80031438 DF410020 */  ld         $at, 0x20($k0) /* handwritten instruction */
    /* 3203C 8003143C DF420028 */  ld         $v0, 0x28($k0) /* handwritten instruction */
    /* 32040 80031440 03600013 */  mtlo       $k1
    /* 32044 80031444 DF5B0110 */  ld         $k1, 0x110($k0) /* handwritten instruction */
    /* 32048 80031448 DF430030 */  ld         $v1, 0x30($k0) /* handwritten instruction */
    /* 3204C 8003144C DF440038 */  ld         $a0, 0x38($k0) /* handwritten instruction */
    /* 32050 80031450 DF450040 */  ld         $a1, 0x40($k0) /* handwritten instruction */
    /* 32054 80031454 DF460048 */  ld         $a2, 0x48($k0) /* handwritten instruction */
    /* 32058 80031458 DF470050 */  ld         $a3, 0x50($k0) /* handwritten instruction */
    /* 3205C 8003145C DF480058 */  ld         $t0, 0x58($k0) /* handwritten instruction */
    /* 32060 80031460 DF490060 */  ld         $t1, 0x60($k0) /* handwritten instruction */
    /* 32064 80031464 DF4A0068 */  ld         $t2, 0x68($k0) /* handwritten instruction */
    /* 32068 80031468 DF4B0070 */  ld         $t3, 0x70($k0) /* handwritten instruction */
    /* 3206C 8003146C DF4C0078 */  ld         $t4, 0x78($k0) /* handwritten instruction */
    /* 32070 80031470 DF4D0080 */  ld         $t5, 0x80($k0) /* handwritten instruction */
    /* 32074 80031474 DF4E0088 */  ld         $t6, 0x88($k0) /* handwritten instruction */
    /* 32078 80031478 DF4F0090 */  ld         $t7, 0x90($k0) /* handwritten instruction */
    /* 3207C 8003147C DF500098 */  ld         $s0, 0x98($k0) /* handwritten instruction */
    /* 32080 80031480 DF5100A0 */  ld         $s1, 0xA0($k0) /* handwritten instruction */
    /* 32084 80031484 DF5200A8 */  ld         $s2, 0xA8($k0) /* handwritten instruction */
    /* 32088 80031488 DF5300B0 */  ld         $s3, 0xB0($k0) /* handwritten instruction */
    /* 3208C 8003148C DF5400B8 */  ld         $s4, 0xB8($k0) /* handwritten instruction */
    /* 32090 80031490 DF5500C0 */  ld         $s5, 0xC0($k0) /* handwritten instruction */
    /* 32094 80031494 DF5600C8 */  ld         $s6, 0xC8($k0) /* handwritten instruction */
    /* 32098 80031498 DF5700D0 */  ld         $s7, 0xD0($k0) /* handwritten instruction */
    /* 3209C 8003149C DF5800D8 */  ld         $t8, 0xD8($k0) /* handwritten instruction */
    /* 320A0 800314A0 DF5900E0 */  ld         $t9, 0xE0($k0) /* handwritten instruction */
    /* 320A4 800314A4 DF5C00E8 */  ld         $gp, 0xE8($k0) /* handwritten instruction */
    /* 320A8 800314A8 03600011 */  mthi       $k1
    /* 320AC 800314AC DF5D00F0 */  ld         $sp, 0xF0($k0) /* handwritten instruction */
    /* 320B0 800314B0 DF5E00F8 */  ld         $fp, 0xF8($k0) /* handwritten instruction */
    /* 320B4 800314B4 DF5F0100 */  ld         $ra, 0x100($k0) /* handwritten instruction */
    /* 320B8 800314B8 8F5B011C */  lw         $k1, 0x11C($k0) /* handwritten instruction */
    /* 320BC 800314BC 409B7000 */  mtc0       $k1, $14 /* handwritten instruction */
    /* 320C0 800314C0 8F5B0018 */  lw         $k1, 0x18($k0) /* handwritten instruction */
    /* 320C4 800314C4 13600013 */  beqz       $k1, .L80031514_32114 /* handwritten instruction */
    /* 320C8 800314C8 00000000 */   nop
    /* 320CC 800314CC 8F5B012C */  lw         $k1, 0x12C($k0) /* handwritten instruction */
    /* 320D0 800314D0 44DBF800 */  ctc1       $k1, $31
    /* 320D4 800314D4 D7400130 */  ldc1       $f0, 0x130($k0)
    /* 320D8 800314D8 D7420138 */  ldc1       $f2, 0x138($k0)
    /* 320DC 800314DC D7440140 */  ldc1       $f4, 0x140($k0)
    /* 320E0 800314E0 D7460148 */  ldc1       $f6, 0x148($k0)
    /* 320E4 800314E4 D7480150 */  ldc1       $f8, 0x150($k0)
    /* 320E8 800314E8 D74A0158 */  ldc1       $f10, 0x158($k0)
    /* 320EC 800314EC D74C0160 */  ldc1       $f12, 0x160($k0)
    /* 320F0 800314F0 D74E0168 */  ldc1       $f14, 0x168($k0)
    /* 320F4 800314F4 D7500170 */  ldc1       $f16, 0x170($k0)
    /* 320F8 800314F8 D7520178 */  ldc1       $f18, 0x178($k0)
    /* 320FC 800314FC D7540180 */  ldc1       $f20, 0x180($k0)
    /* 32100 80031500 D7560188 */  ldc1       $f22, 0x188($k0)
    /* 32104 80031504 D7580190 */  ldc1       $f24, 0x190($k0)
    /* 32108 80031508 D75A0198 */  ldc1       $f26, 0x198($k0)
    /* 3210C 8003150C D75C01A0 */  ldc1       $f28, 0x1A0($k0)
    /* 32110 80031510 D75E01A8 */  ldc1       $f30, 0x1A8($k0)
  .L80031514_32114:
    /* 32114 80031514 8F5B0128 */  lw         $k1, 0x128($k0) /* handwritten instruction */
    /* 32118 80031518 3C1A8004 */  lui        $k0, %hi(__OSGlobalIntMask) /* handwritten instruction */
    /* 3211C 8003151C 275AD400 */  addiu      $k0, $k0, %lo(__OSGlobalIntMask) /* handwritten instruction */
    /* 32120 80031520 8F5A0000 */  lw         $k0, 0x0($k0) /* handwritten instruction */
    /* 32124 80031524 001AD402 */  srl        $k0, $k0, 16
    /* 32128 80031528 037AD824 */  and        $k1, $k1, $k0
    /* 3212C 8003152C 001BD840 */  sll        $k1, $k1, 1
    /* 32130 80031530 3C1A8004 */  lui        $k0, %hi(__osRcpImTable) /* handwritten instruction */
    /* 32134 80031534 275AF0E0 */  addiu      $k0, $k0, %lo(__osRcpImTable) /* handwritten instruction */
    /* 32138 80031538 037AD821 */  addu       $k1, $k1, $k0
    /* 3213C 8003153C 977B0000 */  lhu        $k1, 0x0($k1) /* handwritten instruction */
    /* 32140 80031540 3C1AA430 */  lui        $k0, %hi(D_A430000C) /* handwritten instruction */
    /* 32144 80031544 275A000C */  addiu      $k0, $k0, %lo(D_A430000C) /* handwritten instruction */
    /* 32148 80031548 AF5B0000 */  sw         $k1, 0x0($k0) /* handwritten instruction */
    /* 3214C 8003154C 00000000 */  nop
    /* 32150 80031550 00000000 */  nop
    /* 32154 80031554 00000000 */  nop
    /* 32158 80031558 00000000 */  nop
    /* 3215C 8003155C 42000018 */  eret /* handwritten instruction */
.size __osDispatchThread, . - __osDispatchThread

glabel __osCleanupThread
    /* 32160 80031560 0C00C228 */  jal        osDestroyThread
    /* 32164 80031564 00002025 */   or        $a0, $zero, $zero
    /* 32168 80031568 00000000 */  nop
    /* 3216C 8003156C 00000000 */  nop
.size __osCleanupThread, . - __osCleanupThread
