.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osGetCount
    /* 34090 80033490 40024800 */  mfc0       $v0, $9 /* handwritten instruction */
    /* 34094 80033494 03E00008 */  jr         $ra
    /* 34098 80033498 00000000 */   nop
    /* 3409C 8003349C 00000000 */  nop
.size osGetCount, . - osGetCount
