.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osGetSR
    /* 33280 80032680 40026000 */  mfc0       $v0, $12 /* handwritten instruction */
    /* 33284 80032684 03E00008 */  jr         $ra
    /* 33288 80032688 00000000 */   nop
    /* 3328C 8003268C 00000000 */  nop
.size __osGetSR, . - __osGetSR
