.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osSetWatchLo
    /* 3A2B0 800396B0 40849000 */  mtc0       $a0, $18 /* handwritten instruction */
    /* 3A2B4 800396B4 00000000 */  nop
    /* 3A2B8 800396B8 03E00008 */  jr         $ra
    /* 3A2BC 800396BC 00000000 */   nop
.size __osSetWatchLo, . - __osSetWatchLo
