.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osDisableInt
    /* 36420 80035820 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 36424 80035824 2401FFFE */  addiu      $at, $zero, -0x2
    /* 36428 80035828 01014824 */  and        $t1, $t0, $at
    /* 3642C 8003582C 40896000 */  mtc0       $t1, $12 /* handwritten instruction */
    /* 36430 80035830 31020001 */  andi       $v0, $t0, 0x1
    /* 36434 80035834 00000000 */  nop
    /* 36438 80035838 03E00008 */  jr         $ra
    /* 3643C 8003583C 00000000 */   nop
.size __osDisableInt, . - __osDisableInt

/* Handwritten function */
glabel __osRestoreInt
    /* 36440 80035840 40086000 */  mfc0       $t0, $12 /* handwritten instruction */
    /* 36444 80035844 01044025 */  or         $t0, $t0, $a0
    /* 36448 80035848 40886000 */  mtc0       $t0, $12 /* handwritten instruction */
    /* 3644C 8003584C 00000000 */  nop
    /* 36450 80035850 00000000 */  nop
    /* 36454 80035854 03E00008 */  jr         $ra
    /* 36458 80035858 00000000 */   nop
    /* 3645C 8003585C 00000000 */  nop
.size __osRestoreInt, . - __osRestoreInt
