.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osInvalDCache
    /* 35130 80034530 18A0001F */  blez       $a1, .L800345B0_351B0
    /* 35134 80034534 00000000 */   nop
    /* 35138 80034538 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 3513C 8003453C 00AB082B */  sltu       $at, $a1, $t3
    /* 35140 80034540 1020001D */  beqz       $at, .L800345B8_351B8
    /* 35144 80034544 00000000 */   nop
    /* 35148 80034548 00804025 */  or         $t0, $a0, $zero
    /* 3514C 8003454C 00854821 */  addu       $t1, $a0, $a1
    /* 35150 80034550 0109082B */  sltu       $at, $t0, $t1
    /* 35154 80034554 10200016 */  beqz       $at, .L800345B0_351B0
    /* 35158 80034558 00000000 */   nop
    /* 3515C 8003455C 310A000F */  andi       $t2, $t0, 0xF
    /* 35160 80034560 11400007 */  beqz       $t2, .L80034580_35180
    /* 35164 80034564 2529FFF0 */   addiu     $t1, $t1, -0x10
    /* 35168 80034568 010A4023 */  subu       $t0, $t0, $t2
    /* 3516C 8003456C BD150000 */  cache      0x15, 0x0($t0) /* handwritten instruction */
    /* 35170 80034570 0109082B */  sltu       $at, $t0, $t1
    /* 35174 80034574 1020000E */  beqz       $at, .L800345B0_351B0
    /* 35178 80034578 00000000 */   nop
    /* 3517C 8003457C 25080010 */  addiu      $t0, $t0, 0x10
  .L80034580_35180:
    /* 35180 80034580 312A000F */  andi       $t2, $t1, 0xF
    /* 35184 80034584 11400006 */  beqz       $t2, .L800345A0_351A0
    /* 35188 80034588 00000000 */   nop
    /* 3518C 8003458C 012A4823 */  subu       $t1, $t1, $t2
    /* 35190 80034590 BD350010 */  cache      0x15, 0x10($t1) /* handwritten instruction */
    /* 35194 80034594 0128082B */  sltu       $at, $t1, $t0
    /* 35198 80034598 14200005 */  bnez       $at, .L800345B0_351B0
    /* 3519C 8003459C 00000000 */   nop
  .L800345A0_351A0:
    /* 351A0 800345A0 BD110000 */  cache      0x11, 0x0($t0) /* handwritten instruction */
    /* 351A4 800345A4 0109082B */  sltu       $at, $t0, $t1
    /* 351A8 800345A8 1420FFFD */  bnez       $at, .L800345A0_351A0
    /* 351AC 800345AC 25080010 */   addiu     $t0, $t0, 0x10
  .L800345B0_351B0:
    /* 351B0 800345B0 03E00008 */  jr         $ra
    /* 351B4 800345B4 00000000 */   nop
  .L800345B8_351B8:
    /* 351B8 800345B8 3C088000 */  lui        $t0, 0x8000
    /* 351BC 800345BC 010B4821 */  addu       $t1, $t0, $t3
    /* 351C0 800345C0 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L800345C4_351C4:
    /* 351C4 800345C4 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 351C8 800345C8 0109082B */  sltu       $at, $t0, $t1
    /* 351CC 800345CC 1420FFFD */  bnez       $at, .L800345C4_351C4
    /* 351D0 800345D0 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 351D4 800345D4 03E00008 */  jr         $ra
    /* 351D8 800345D8 00000000 */   nop
    /* 351DC 800345DC 00000000 */  nop
.size osInvalDCache, . - osInvalDCache
