.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osInvalICache
    /* 350B0 800344B0 18A00011 */  blez       $a1, .L800344F8_350F8
    /* 350B4 800344B4 00000000 */   nop
    /* 350B8 800344B8 240B4000 */  addiu      $t3, $zero, 0x4000
    /* 350BC 800344BC 00AB082B */  sltu       $at, $a1, $t3
    /* 350C0 800344C0 1020000F */  beqz       $at, .L80034500_35100
    /* 350C4 800344C4 00000000 */   nop
    /* 350C8 800344C8 00804025 */  or         $t0, $a0, $zero
    /* 350CC 800344CC 00854821 */  addu       $t1, $a0, $a1
    /* 350D0 800344D0 0109082B */  sltu       $at, $t0, $t1
    /* 350D4 800344D4 10200008 */  beqz       $at, .L800344F8_350F8
    /* 350D8 800344D8 00000000 */   nop
    /* 350DC 800344DC 310A001F */  andi       $t2, $t0, 0x1F
    /* 350E0 800344E0 2529FFE0 */  addiu      $t1, $t1, -0x20
    /* 350E4 800344E4 010A4023 */  subu       $t0, $t0, $t2
  .L800344E8_350E8:
    /* 350E8 800344E8 BD100000 */  cache      0x10, 0x0($t0) /* handwritten instruction */
    /* 350EC 800344EC 0109082B */  sltu       $at, $t0, $t1
    /* 350F0 800344F0 1420FFFD */  bnez       $at, .L800344E8_350E8
    /* 350F4 800344F4 25080020 */   addiu     $t0, $t0, 0x20
  .L800344F8_350F8:
    /* 350F8 800344F8 03E00008 */  jr         $ra
    /* 350FC 800344FC 00000000 */   nop
  .L80034500_35100:
    /* 35100 80034500 3C088000 */  lui        $t0, 0x8000
    /* 35104 80034504 010B4821 */  addu       $t1, $t0, $t3
    /* 35108 80034508 2529FFE0 */  addiu      $t1, $t1, -0x20
  .L8003450C_3510C:
    /* 3510C 8003450C BD000000 */  cache      0x00, 0x0($t0) /* handwritten instruction */
    /* 35110 80034510 0109082B */  sltu       $at, $t0, $t1
    /* 35114 80034514 1420FFFD */  bnez       $at, .L8003450C_3510C
    /* 35118 80034518 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
    /* 3511C 8003451C 03E00008 */  jr         $ra
    /* 35120 80034520 00000000 */   nop
    /* 35124 80034524 00000000 */  nop
    /* 35128 80034528 00000000 */  nop
    /* 3512C 8003452C 00000000 */  nop
.size osInvalICache, . - osInvalICache
