.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osMapTLBRdb
    /* 36EB0 800362B0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 36EB4 800362B4 2409001F */  addiu      $t1, $zero, 0x1F
    /* 36EB8 800362B8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 36EBC 800362BC 40802800 */  mtc0       $zero, $5 /* handwritten instruction */
    /* 36EC0 800362C0 240A0017 */  addiu      $t2, $zero, 0x17
    /* 36EC4 800362C4 3C09C000 */  lui        $t1, (0xC0000000 >> 16)
    /* 36EC8 800362C8 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 36ECC 800362CC 3C098000 */  lui        $t1, (0x80000000 >> 16)
    /* 36ED0 800362D0 00095982 */  srl        $t3, $t1, 6
    /* 36ED4 800362D4 016A5825 */  or         $t3, $t3, $t2
    /* 36ED8 800362D8 408B1000 */  mtc0       $t3, $2 /* handwritten instruction */
    /* 36EDC 800362DC 24090001 */  addiu      $t1, $zero, 0x1
    /* 36EE0 800362E0 40891800 */  mtc0       $t1, $3 /* handwritten instruction */
    /* 36EE4 800362E4 00000000 */  nop
    /* 36EE8 800362E8 42000002 */  tlbwi /* handwritten instruction */
    /* 36EEC 800362EC 00000000 */  nop
    /* 36EF0 800362F0 00000000 */  nop
    /* 36EF4 800362F4 00000000 */  nop
    /* 36EF8 800362F8 00000000 */  nop
    /* 36EFC 800362FC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 36F00 80036300 03E00008 */  jr         $ra
    /* 36F04 80036304 00000000 */   nop
    /* 36F08 80036308 00000000 */  nop
    /* 36F0C 8003630C 00000000 */  nop
.size osMapTLBRdb, . - osMapTLBRdb
