.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osProbeTLB
    /* 33820 80032C20 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 33824 80032C24 310900FF */  andi       $t1, $t0, 0xFF
    /* 33828 80032C28 2401E000 */  addiu      $at, $zero, -0x2000
    /* 3382C 80032C2C 00815024 */  and        $t2, $a0, $at
    /* 33830 80032C30 012A4825 */  or         $t1, $t1, $t2
    /* 33834 80032C34 40895000 */  mtc0       $t1, $10 /* handwritten instruction */
    /* 33838 80032C38 00000000 */  nop
    /* 3383C 80032C3C 00000000 */  nop
    /* 33840 80032C40 00000000 */  nop
    /* 33844 80032C44 42000008 */  tlbp /* handwritten instruction */
    /* 33848 80032C48 00000000 */  nop
    /* 3384C 80032C4C 00000000 */  nop
    /* 33850 80032C50 400B0000 */  mfc0       $t3, $0 /* handwritten instruction */
    /* 33854 80032C54 3C018000 */  lui        $at, (0x80000000 >> 16)
    /* 33858 80032C58 01615824 */  and        $t3, $t3, $at
    /* 3385C 80032C5C 1560001A */  bnez       $t3, .L80032CC8_338C8
    /* 33860 80032C60 00000000 */   nop
    /* 33864 80032C64 42000001 */  tlbr /* handwritten instruction */
    /* 33868 80032C68 00000000 */  nop
    /* 3386C 80032C6C 00000000 */  nop
    /* 33870 80032C70 00000000 */  nop
    /* 33874 80032C74 400B2800 */  mfc0       $t3, $5 /* handwritten instruction */
    /* 33878 80032C78 216B2000 */  addi       $t3, $t3, 0x2000 /* handwritten instruction */
    /* 3387C 80032C7C 000B5842 */  srl        $t3, $t3, 1
    /* 33880 80032C80 01646024 */  and        $t4, $t3, $a0
    /* 33884 80032C84 15800004 */  bnez       $t4, .L80032C98_33898
    /* 33888 80032C88 216BFFFF */   addi      $t3, $t3, -0x1 /* handwritten instruction */
    /* 3388C 80032C8C 40021000 */  mfc0       $v0, $2 /* handwritten instruction */
    /* 33890 80032C90 10000002 */  b          .L80032C9C_3389C
    /* 33894 80032C94 00000000 */   nop
  .L80032C98_33898:
    /* 33898 80032C98 40021800 */  mfc0       $v0, $3 /* handwritten instruction */
  .L80032C9C_3389C:
    /* 3389C 80032C9C 304D0002 */  andi       $t5, $v0, 0x2
    /* 338A0 80032CA0 11A00009 */  beqz       $t5, .L80032CC8_338C8
    /* 338A4 80032CA4 00000000 */   nop
    /* 338A8 80032CA8 3C013FFF */  lui        $at, (0x3FFFFFC0 >> 16)
    /* 338AC 80032CAC 3421FFC0 */  ori        $at, $at, (0x3FFFFFC0 & 0xFFFF)
    /* 338B0 80032CB0 00411024 */  and        $v0, $v0, $at
    /* 338B4 80032CB4 00021180 */  sll        $v0, $v0, 6
    /* 338B8 80032CB8 008B6824 */  and        $t5, $a0, $t3
    /* 338BC 80032CBC 004D1020 */  add        $v0, $v0, $t5 /* handwritten instruction */
    /* 338C0 80032CC0 10000002 */  b          .L80032CCC_338CC
    /* 338C4 80032CC4 00000000 */   nop
  .L80032CC8_338C8:
    /* 338C8 80032CC8 2402FFFF */  addiu      $v0, $zero, -0x1
  .L80032CCC_338CC:
    /* 338CC 80032CCC 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 338D0 80032CD0 03E00008 */  jr         $ra
    /* 338D4 80032CD4 00000000 */   nop
    /* 338D8 80032CD8 00000000 */  nop
    /* 338DC 80032CDC 00000000 */  nop
.size __osProbeTLB, . - __osProbeTLB
