.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osSetCompare
    /* 36010 80035410 40845800 */  mtc0       $a0, $11 /* handwritten instruction */
    /* 36014 80035414 03E00008 */  jr         $ra
    /* 36018 80035418 00000000 */   nop
    /* 3601C 8003541C 00000000 */  nop
.size __osSetCompare, . - __osSetCompare
