.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

glabel __osSetFpcCsr
    /* 36D40 80036140 4442F800 */  cfc1       $v0, $31
    /* 36D44 80036144 44C4F800 */  ctc1       $a0, $31
    /* 36D48 80036148 03E00008 */  jr         $ra
    /* 36D4C 8003614C 00000000 */   nop
.size __osSetFpcCsr, . - __osSetFpcCsr
