.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .rodata, "a"

/* Generated by spimdisasm 1.35.0 */

dlabel __osRcpImTable
    .short 0x0555
    .short 0x0556
    .short 0x0559
    .short 0x055A
    .short 0x0565
    .short 0x0566
    .short 0x0569
    .short 0x056A
    .short 0x0595
    .short 0x0596
    .short 0x0599
    .short 0x059A
    .short 0x05A5
    .short 0x05A6
    .short 0x05A9
    .short 0x05AA
    .short 0x0655
    .short 0x0656
    .short 0x0659
    .short 0x065A
    .short 0x0665
    .short 0x0666
    .short 0x0669
    .short 0x066A
    .short 0x0695
    .short 0x0696
    .short 0x0699
    .short 0x069A
    .short 0x06A5
    .short 0x06A6
    .short 0x06A9
    .short 0x06AA
    .short 0x0955
    .short 0x0956
    .short 0x0959
    .short 0x095A
    .short 0x0965
    .short 0x0966
    .short 0x0969
    .short 0x096A
    .short 0x0995
    .short 0x0996
    .short 0x0999
    .short 0x099A
    .short 0x09A5
    .short 0x09A6
    .short 0x09A9
    .short 0x09AA
    .short 0x0A55
    .short 0x0A56
    .short 0x0A59
    .short 0x0A5A
    .short 0x0A65
    .short 0x0A66
    .short 0x0A69
    .short 0x0A6A
    .short 0x0A95
    .short 0x0A96
    .short 0x0A99
    .short 0x0A9A
    .short 0x0AA5
    .short 0x0AA6
    .short 0x0AA9
    .short 0x0AAA
.size __osRcpImTable, . - __osRcpImTable

.section .text, "ax"

/* Generated by spimdisasm 1.35.0 */

/* Handwritten function */
glabel osSetIntMask
    /* 30F50 80030350 400C6000 */  mfc0       $t4, $12 /* handwritten instruction */
    /* 30F54 80030354 3182FF01 */  andi       $v0, $t4, 0xFF01
    /* 30F58 80030358 3C088004 */  lui        $t0, %hi(__OSGlobalIntMask)
    /* 30F5C 8003035C 2508D400 */  addiu      $t0, $t0, %lo(__OSGlobalIntMask)
    /* 30F60 80030360 8D0B0000 */  lw         $t3, 0x0($t0)
    /* 30F64 80030364 2401FFFF */  addiu      $at, $zero, -0x1
    /* 30F68 80030368 01614026 */  xor        $t0, $t3, $at
    /* 30F6C 8003036C 3108FF00 */  andi       $t0, $t0, 0xFF00
    /* 30F70 80030370 00481025 */  or         $v0, $v0, $t0
    /* 30F74 80030374 3C0AA430 */  lui        $t2, %hi(MI_INTR_MASK_REG)
    /* 30F78 80030378 8D4A000C */  lw         $t2, %lo(MI_INTR_MASK_REG)($t2)
    /* 30F7C 8003037C 11400005 */  beqz       $t2, .L80030394_30F94
    /* 30F80 80030380 000B4C02 */   srl       $t1, $t3, 16
    /* 30F84 80030384 2401FFFF */  addiu      $at, $zero, -0x1
    /* 30F88 80030388 01214826 */  xor        $t1, $t1, $at
    /* 30F8C 8003038C 3129003F */  andi       $t1, $t1, 0x3F
    /* 30F90 80030390 01495025 */  or         $t2, $t2, $t1
  .L80030394_30F94:
    /* 30F94 80030394 000A5400 */  sll        $t2, $t2, 16
    /* 30F98 80030398 004A1025 */  or         $v0, $v0, $t2
    /* 30F9C 8003039C 3C01003F */  lui        $at, (0x3F0000 >> 16)
    /* 30FA0 800303A0 00814024 */  and        $t0, $a0, $at
    /* 30FA4 800303A4 010B4024 */  and        $t0, $t0, $t3
    /* 30FA8 800303A8 000843C2 */  srl        $t0, $t0, 15
    /* 30FAC 800303AC 3C0A8004 */  lui        $t2, %hi(__osRcpImTable)
    /* 30FB0 800303B0 01485021 */  addu       $t2, $t2, $t0
    /* 30FB4 800303B4 954AF0E0 */  lhu        $t2, %lo(__osRcpImTable)($t2)
    /* 30FB8 800303B8 3C01A430 */  lui        $at, %hi(MI_INTR_MASK_REG)
    /* 30FBC 800303BC AC2A000C */  sw         $t2, %lo(MI_INTR_MASK_REG)($at)
    /* 30FC0 800303C0 3088FF01 */  andi       $t0, $a0, 0xFF01
    /* 30FC4 800303C4 3169FF00 */  andi       $t1, $t3, 0xFF00
    /* 30FC8 800303C8 01094024 */  and        $t0, $t0, $t1
    /* 30FCC 800303CC 3C01FFFF */  lui        $at, (0xFFFF00FF >> 16)
    /* 30FD0 800303D0 342100FF */  ori        $at, $at, (0xFFFF00FF & 0xFFFF)
    /* 30FD4 800303D4 01816024 */  and        $t4, $t4, $at
    /* 30FD8 800303D8 01886025 */  or         $t4, $t4, $t0
    /* 30FDC 800303DC 408C6000 */  mtc0       $t4, $12 /* handwritten instruction */
    /* 30FE0 800303E0 00000000 */  nop
    /* 30FE4 800303E4 00000000 */  nop
    /* 30FE8 800303E8 03E00008 */  jr         $ra
    /* 30FEC 800303EC 00000000 */   nop
.size osSetIntMask, . - osSetIntMask
