.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel __osSetSR
    /* 33270 80032670 40846000 */  mtc0       $a0, $12 /* handwritten instruction */
    /* 33274 80032674 00000000 */  nop
    /* 33278 80032678 03E00008 */  jr         $ra
    /* 3327C 8003267C 00000000 */   nop
.size __osSetSR, . - __osSetSR
