.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osUnmapTLBAll
    /* 34EB0 800342B0 40085000 */  mfc0       $t0, $10 /* handwritten instruction */
    /* 34EB4 800342B4 2409001E */  addiu      $t1, $zero, 0x1E
    /* 34EB8 800342B8 3C0A8000 */  lui        $t2, (0x80000000 >> 16)
    /* 34EBC 800342BC 408A5000 */  mtc0       $t2, $10 /* handwritten instruction */
    /* 34EC0 800342C0 40801000 */  mtc0       $zero, $2 /* handwritten instruction */
    /* 34EC4 800342C4 40801800 */  mtc0       $zero, $3 /* handwritten instruction */
  .L800342C8_34EC8:
    /* 34EC8 800342C8 40890000 */  mtc0       $t1, $0 /* handwritten instruction */
    /* 34ECC 800342CC 00000000 */  nop
    /* 34ED0 800342D0 42000002 */  tlbwi /* handwritten instruction */
    /* 34ED4 800342D4 00000000 */  nop
    /* 34ED8 800342D8 00000000 */  nop
    /* 34EDC 800342DC 2129FFFF */  addi       $t1, $t1, -0x1 /* handwritten instruction */
    /* 34EE0 800342E0 0521FFF9 */  bgez       $t1, .L800342C8_34EC8
    /* 34EE4 800342E4 00000000 */   nop
    /* 34EE8 800342E8 40885000 */  mtc0       $t0, $10 /* handwritten instruction */
    /* 34EEC 800342EC 03E00008 */  jr         $ra
    /* 34EF0 800342F0 00000000 */   nop
    /* 34EF4 800342F4 00000000 */  nop
    /* 34EF8 800342F8 00000000 */  nop
    /* 34EFC 800342FC 00000000 */  nop
.size osUnmapTLBAll, . - osUnmapTLBAll
