.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osWritebackDCacheAll
    /* 39D60 80039160 3C088000 */  lui        $t0, 0x8000
    /* 39D64 80039164 240A2000 */  addiu      $t2, $zero, 0x2000
    /* 39D68 80039168 010A4821 */  addu       $t1, $t0, $t2
    /* 39D6C 8003916C 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L80039170_39D70:
    /* 39D70 80039170 BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 39D74 80039174 0109082B */  sltu       $at, $t0, $t1
    /* 39D78 80039178 1420FFFD */  bnez       $at, .L80039170_39D70
    /* 39D7C 8003917C 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 39D80 80039180 03E00008 */  jr         $ra
    /* 39D84 80039184 00000000 */   nop
    /* 39D88 80039188 00000000 */  nop
    /* 39D8C 8003918C 00000000 */  nop
.size osWritebackDCacheAll, . - osWritebackDCacheAll
