.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.32.1 */

/* Handwritten function */
glabel osWritebackDCache
    /* 32DD0 800321D0 18A00011 */  blez       $a1, .L80032218_32E18
    /* 32DD4 800321D4 00000000 */   nop
    /* 32DD8 800321D8 240B2000 */  addiu      $t3, $zero, 0x2000
    /* 32DDC 800321DC 00AB082B */  sltu       $at, $a1, $t3
    /* 32DE0 800321E0 1020000F */  beqz       $at, .L80032220_32E20
    /* 32DE4 800321E4 00000000 */   nop
    /* 32DE8 800321E8 00804025 */  or         $t0, $a0, $zero
    /* 32DEC 800321EC 00854821 */  addu       $t1, $a0, $a1
    /* 32DF0 800321F0 0109082B */  sltu       $at, $t0, $t1
    /* 32DF4 800321F4 10200008 */  beqz       $at, .L80032218_32E18
    /* 32DF8 800321F8 00000000 */   nop
    /* 32DFC 800321FC 310A000F */  andi       $t2, $t0, 0xF
    /* 32E00 80032200 2529FFF0 */  addiu      $t1, $t1, -0x10
    /* 32E04 80032204 010A4023 */  subu       $t0, $t0, $t2
  .L80032208_32E08:
    /* 32E08 80032208 BD190000 */  cache      0x19, 0x0($t0) /* handwritten instruction */
    /* 32E0C 8003220C 0109082B */  sltu       $at, $t0, $t1
    /* 32E10 80032210 1420FFFD */  bnez       $at, .L80032208_32E08
    /* 32E14 80032214 25080010 */   addiu     $t0, $t0, 0x10
  .L80032218_32E18:
    /* 32E18 80032218 03E00008 */  jr         $ra
    /* 32E1C 8003221C 00000000 */   nop
  .L80032220_32E20:
    /* 32E20 80032220 3C088000 */  lui        $t0, 0x8000
    /* 32E24 80032224 010B4821 */  addu       $t1, $t0, $t3
    /* 32E28 80032228 2529FFF0 */  addiu      $t1, $t1, -0x10
  .L8003222C_32E2C:
    /* 32E2C 8003222C BD010000 */  cache      0x01, 0x0($t0) /* handwritten instruction */
    /* 32E30 80032230 0109082B */  sltu       $at, $t0, $t1
    /* 32E34 80032234 1420FFFD */  bnez       $at, .L8003222C_32E2C
    /* 32E38 80032238 25080010 */   addiu     $t0, $t0, (0x80000010 & 0xFFFF)
    /* 32E3C 8003223C 03E00008 */  jr         $ra
    /* 32E40 80032240 00000000 */   nop
    /* 32E44 80032244 00000000 */  nop
    /* 32E48 80032248 00000000 */  nop
    /* 32E4C 8003224C 00000000 */  nop
.size osWritebackDCache, . - osWritebackDCache
